@startuml
title <size: 30> US25 Class Diagram

skinparam linetype ortho

interface Sensor {
    + getSensorTypeID() : SensorTypeIDVO
    + getDeviceID() : DeviceIDVO
    + getSensorName() : SensorNameVO
}

class SensorIDVO {
    - indentifier : UUID
    + SensorIDVO(identifier : UUID) : SensorIDVO
    + getID() : String
}

class SensorNameVO {
    - sensorName : String
    + SensorNameVO(sensorName : String) : SensorNameVO
    + getValue() : String
}

class SensorTypeIDVO {
    - sensorTypeID : String
    + SensorTypeIDVO(sensorTypeID : String) : SensorTypeIDVO
    + getID() : String
}

class DeviceIDVO {
    - deviceID : UUID
    + DeviceIDVO(deviceID : UUID) : DeviceIDVO
    + getID() : String
}

interface DomainID {
    + getID() : String
}

interface ValueObject<T> {
    + getValue() : T
}

class AveragePowerConsumptionSensor {
    - sensorID : SensorIDVO
    - sensorName : SensorNameVO
    - sensorTypeID : SensorTypeIDVO
    - deviceID : DeviceIDVO
    + AveragePowerConsumptionSensor(sensorName : SensorNameVO,\n deviceID : DeviceIDVO,\n sensorTypeID : SensorTypeIDVO) : AveragePowerConsumptionSensor
    + getReading(initialDate : String,\n finalDate : String,\n simHardware : SimHardware) : ValueObject<Integer>
    + getSensorName() : SensorNameVO
    + getSensorTypeID() : SensorTypeIDVO
    + getDeviceID() : DeviceIDVO
    + getId() : DomainID
}

class AveragePowerConsumptionValue {
    - averagePowerConsumptionValue : int
    + AveragePowerConsumptionValue(reading : String)\n : AveragePowerConsumptionValue
    + getValue() : Integer
}

class SimHardware {
    + getValue() : String
    + getValue(initialDate : String, finalDate : String) : String
}

interface DomainEntity{
    + getID() : DomainID
}

AveragePowerConsumptionSensor *---down SensorIDVO
AveragePowerConsumptionSensor -down..> SensorTypeIDVO : <<has>>
AveragePowerConsumptionSensor -down..> DeviceIDVO : <<has>>
AveragePowerConsumptionSensor -left..> SensorNameVO : <<has>>
SensorIDVO -down..|> DomainID
SensorTypeIDVO -down..|> DomainID
DeviceIDVO -down..|> DomainID
SensorNameVO -left..|> ValueObject
AveragePowerConsumptionValue -up..|> ValueObject
AveragePowerConsumptionSensor -left..> AveragePowerConsumptionValue : <<creates>>
AveragePowerConsumptionSensor -right..> SimHardware : <<uses>>
AveragePowerConsumptionSensor -up..|> Sensor
Sensor -right--|>DomainEntity

@enduml