@startuml
title <size: 30> HumiditySensor Class Diagram v5.0

note "<b>Only methods related to \n<b>HumiditySensor are represented" as 1

skinparam linetype ortho

interface Sensor {

}

interface SensorExternalServices{
     + getValue() : String
}

interface DomainID{
    + getID() : String
}

interface DomainEntity{
    +getID() : DomainID4
}

interface ValueObject<T> {
    + getValue() : T
}


class HumiditySensor{
    - sensorName : SensorNameVO
    - deviceID : DeviceIDVO
    - sensorTypeID : SensorTypeIDVO
    - sensorID : SensorIDVO

    + HumiditySensor(sensorName : SensorNameVO,deviceID : DeviceIDVO,sensorTypeID : SensorTypeIDVO)
    + getReading(simHardware : SimHardware) : ValueObject<Integer>
}

class HumidityValue{
    - primitiveValue : int

    + HumidityValue(reading: String)
    + getValue() : Integer
}

class SimHardware{
}

class SensorNameVO{
    - sensorName : String
    + SensorNameVO(sensorName : String)
    + getValue() : String
}

class SensorIDVO{
    - identifier : UUID
    + SensorIDVO(identifier : UUID)
}


class SensorTypeIDVO{
    - sensorTypeID : String
    + SensorTypeIDVO(sensorTypeID : String)
}

class DeviceIDVO{
    - deviceID : UUID
    + DeviceIDVO(deviceID : UUID)
}

interface Sensor {
    + getSensorTypeID() : SensorTypeIDVO
    + getDeviceID() : DeviceIDVO
    + getSensorName() : SensorNameVO
}


Sensor <|..left HumiditySensor
SimHardware <.. HumiditySensor

SensorNameVO <.. HumiditySensor
SensorExternalServices <|..down SimHardware
SensorIDVO --* HumiditySensor
HumidityValue *--right HumiditySensor
SensorTypeIDVO <.. HumiditySensor
DeviceIDVO <.. HumiditySensor

ValueObject <|.. SensorNameVO
DomainID  <|.. SensorIDVO
DomainID  <|.. SensorTypeIDVO
DomainID  <|.. DeviceIDVO

ValueObject <|.. HumidityValue
Sensor -up-|> DomainEntity

@enduml