Position Sensor Class Diagram

@startuml
title <size: 30> Position Sensor - Class Diagram v5.1


interface AggregateRoot {
    + getID() : DomainID
}

interface Sensor {
    + getSensorTypeID() : SensorTypeIDVO;
    + getDeviceID() : DeviceIDVO;
    + getSensorName() : SensorNameVO;
}

interface SensorExternalServices {
    + getValue() : String
}


interface ValueObject<T> {
    + getValue() : T
}

class SensorNameVO{
    - sensorName : String
    + getValue() : String
}

class DeviceIDVO{
    - deviceID : UUID
    + getID : String
}

class SensorTypeIDVO{
    - sensorTypeID : String
    + getID() : String
}

class SensorIDVO{
    - identifier : UUID
    + getValue() : String
}


class PositionSensor{
    - sensorName : SensorNameVO
    - deviceID : DeviceIDVO
    - sensorType : SensorTypeIDVO
    - sensorID : SensorIDVO

    + getReading(simHardware : SensorExternalServices) : ValueObject<Integer>
}

class PositionValue{
    - position : int

    + getValue() : Integer
    - isReadingValid(positionValue : int) : boolean
}

class SimHardware{
    + getValue() : String
}

interface DomainID {
    + getID() : String
}

Sensor --right|> AggregateRoot
ValueObject <|.. PositionValue
Sensor <|.. PositionSensor
SensorExternalServices <|.. SimHardware
PositionSensor .right.> PositionValue
PositionSensor .left.> SimHardware
PositionSensor "1" *--right "1" SensorNameVO
PositionSensor "*" o-- "1" DeviceIDVO
PositionSensor "1" *--down "1" SensorTypeIDVO
PositionSensor "1" *--down "1" SensorIDVO
DeviceIDVO ..|> DomainID
SensorTypeIDVO ..|> DomainID
SensorIDVO ..|> DomainID
SensorNameVO ..|> ValueObject
@enduml