@startuml
       title <size: 30> US03 Class Diagram
       note "<b>Only methods related to\n<b>US03 are represented" as N1

       class CommonListOfRooms{
           - house : House
           - roomDTOAndRoomMap : LinkedHashMap<RoomDTO, Room>

           + getListOfRooms() : List<RoomDTO
           - truncateList(roomDTOAndRoomMap : Map<RoomDTO, Room>) : List<RoomDTO>
           - refreshMap() : void
       }

       class RoomDTOMapper{
           + getRoomDTOList(listOfRooms : List<Room>) : LinkedHashMap<RoomDTO, Room>
           + domainToDTO(room : Room) : RoomDTO
       }

       class House {
           - houseName: String
           - gps : GPS
           - address : Address
           - listOfRooms : ListOfRooms

           + getListOfRooms() : List<Room>
       }

       class ListOfRooms{
           - roomList : ArrayList<Room>

           + getRoomList () : List<Room>
       }

       class GetListOfRoomsCTRL{
            - house : House
            - commonListOfRooms : CommonListOfRooms

            +getListOfRooms() : List<RoomDTO>
        }

       class RoomDTO{
            - roomName :String
            - houseFloor : int
            - roomWidth : double
            - roomLength : double
            - roomHeight : double

               }

       GetListOfRoomsCTRL ..> CommonListOfRooms
       RoomDTOMapper ..> RoomDTO
       CommonListOfRooms ..> House
       House "1" *-- "1" ListOfRooms
       CommonListOfRooms ..> RoomDTOMapper

       @enduml