@startuml

skinparam ParticipantPadding 50
autonumber
title User Story 3 - Main Success Scenario

participant ":GetListOfRoomsCTRL" as C
participant ":CommonListOfRooms" as CU
participant ":House" as H
participant ":ListOfRooms" as LR
participant ":RoomDTOMapper" as RM
participant ":Room" as R

[o-> C : getListOfRooms()
activate C
C -> CU : getListOfRooms()
activate CU
CU -> H : getListOfRooms()
activate H
H -> LR : getRoomList()
activate LR
LR --> H : roomList
deactivate LR
H --> CU : roomList
deactivate H
CU -> RM : getRoomDTOList(roomList)
activate RM
loop for each room in room list
RM -> RM : RoomDTO = domainToDTO(room)
activate RM
deactivate RM
RM -> RM : put(RoomDTO, room)
activate RM
deactivate RM
end loop
RM --> CU : roomDTOAndRoomMap
deactivate RM
CU -> CU : truncateList(roomDTOAndRoomMap)
activate CU
deactivate CU
CU --> C : roomDtoList
deactivate CU
[o<-- C : roomDtoList
deactivate C

@enduml