@startuml

skinparam ParticipantPadding 50
autonumber
title User Story 3 - Main Success Scenario

participant ":GetListOfRoomsCTRL" as C
participant ":RoomRepository" as RR
participant ":RoomDTOMapper" as RM

[o-> C : getListOfRooms()
activate C
C -> RR : getListOfRooms()
activate RR
RR -> RR : cloneListOfRooms()
RR --> C : clonedListOfRooms
deactivate RR

C -> RM : RoomDTO = domainToDTO(room)

activate RM
loop for each room in room list
RM -> RM : RoomDTO = domainToDTO(room)
activate RM
deactivate RM
RM -> RM : put(RoomDTO, room)
activate RM
deactivate RM
end loop
RM --> C : roomDTOAndRoomMap




@enduml