@startuml
title <size: 30> US11 Class Diagram

interface Sensor {
    + continuousMeasure() : void
    + getLastReading() : String
    + getName() : String
    + getType() : SensorTypeOptions
}

class HumiditySensor{
    - sensorName : String
    - TYPE : SensorTypeOptions
    - reading : double
    - log : ArrayList<String>
    - addToLog((reading : double) : void
}

Sensor <|.. HumiditySensor

@enduml