@startuml
title <size: 30> US26 Class Diagram


interface Sensor {
    + getName() : String
    + getUnit() : String
    + getLog() : ArrayList<String>
}

interface Value<T> {
    + getValue() : T
    + getValueAsString() : String
}

class SimHardware {
+ getvalue(initialDate : String, finalDate : String) : boolean
}

interface ExternalServices{}

class EnergyConsumptionSensor{
    - sensorName : String
    - unit : String
    -Type : String
    - simHardware : SimHardware
    - log : ArrayList<Value<Integer>>

    -validateSensorName(sensorName : String) : boolean
    +getReading() : Value<Integer>
    -getInitialDateTime(initialDate : String) : LocalDateTime
    -getFinalDateTime(finalDate : String) : LocalDateTime
    -validateDate(initialDate : LocalDateTime, finalDateTime : LocalDateTime) : boolean
    +getName() : String
    +getUnit() : String
    +getLog() : ArrayList<String>
    +getType() : String
    -addLog(value : Value<Integer>) : void

}

class EnergyConsumptionValue {
    - primitiveValue : Integer

    - validateReading(reading : String) : boolean
    + getValue() : Integer
    + getValueAsString() : String
}

Value <|.. EnergyConsumptionValue
Sensor <|.. EnergyConsumptionSensor
ExternalServices <|.. SimHardware
EnergyConsumptionSensor <|.. SimHardware
EnergyConsumptionSensor .right.> EnergyConsumptionValue


@enduml