@startuml
autonumber
title User Story 2 - Main Success Scenario
participant ":AddRoomToHouseCTRL" as C
participant ":RoomMapper" as Rm
participant ":HouseRepo" as Hr
participant ":ImpFactoryRoom" as fR
participant "r1 : Room" as R
participant ":RepoRoom" as rR
skinparam ParticipantPadding 50

[o-> C : addRoomToHouse(roomNameDTO, \nroomDimensionsDTO, roomFloorDTO)
activate C
C -> Rm : roomName = roomNameDTOtoRoomName(roomNameDTO)
C -> Rm : roomDimensions = roomDimensionsDTOtoRoomDimensions(roomDimensionsDTO)
C -> Rm : roomFloor = roomFloorDTOtoRoomFloor(roomFloorDTO)
C -> Hr : houseID = gethouseID()
C -> fR : r1 = newRoom(houseID, roomName, \nroomDimensions, roomFloor)


activate fR
fR -> R** : newRoom(houseID, roomName,\nroomDimensions, roomFloor)
deactivate fR

C -> rR : boolean = addRoom(r1)
[o<-- C : Room Added!
deactivate C


@enduml
