@startuml

title <size: 30> US02 Class Diagram
note "<b>Only methods related to\n<b>US02 are represented" as N1
skinparam linetype ortho

interface Repository {
}

class RoomMapper {
    + roomDTOtoRoomName(roomDTO : RoomDTO) : RoomNameVO
    + roomDTOtoRoomFloor(roomDTO : RoomDTO) : RoomFloorVO
    + roomDTOtoRoomDimensions(roomDTO : RoomsDTO) : RoomDimensionsVO
}

class HouseService {
    + houseRepo : HouseRepo

    + getHouseID() : HouseIDVO
}

class AddRoomToHouseCTRL {
    - houseService : HouseService
    - roomService : RoomService
    - roomMapper : RoomMapper

    + addRoom(roomDTO : RoomDTO) : Room
    + save(room Room) : boolean
    - getHouseID() : HouseIDVO
}

class RoomService {
    - RoomRepo roomRepo;
    - RoomFactory RoomFactory;

    + createRoom (roomName : RoomNameVO, roomFloor : RoomFloorVO, \nroomDimensions : RoomDimensionsVO, houseID : House IDVO) : Room
    + save (room : Room) : boolean
}

class Room {
    - houseID: HouseIDVO
    - roomName: RoomNameVO
    - room ID: RoomIDVO
    - roomFloor : RoomFloorVO
    - dimensions : RoomDimensionsVO
}

class RoomDimensionsVO{
     - roomWidth : RoomWidth
     - roomLength : RoomLength
     - roomHeight : RoomHeight
}

class RoomWidthVO{
     - roomWidth : double
}

class RoomLengthVO{
     - roomLength : double
}

class RoomHeightVO{
     - roomHeight : double
}

class RoomIDVO{
     - roomID : int
}

class RoomNameVO{
     - roomName : String
}

class RoomFloorVO{
     - roomFloor : int
}

class HouseIDVO{
     - houseID : int
}
class HouseRepo{
    + getHouseID() : HouseIDVO
}

class RoomFactory{
    + createRoom (roomName : RoomNameVO, roomFloor : RoomFloorVO, \nroomDimensions : RoomDimensionsVO, houseID : House IDVO) : Room
}
class RoomRepo{
    + roomMap : HashMap<RoomIDVO, Room>
    + save(room : Room ) : boolean
}

AddRoomToHouseCTRL ..> RoomMapper
AddRoomToHouseCTRL ..right> HouseService
AddRoomToHouseCTRL ..> RoomService
RoomService ..> RoomFactory
HouseService ..> HouseRepo
RoomService ..> RoomRepo
RoomFactory ..> Room
HouseRepo <|.. Repository
RoomRepo <|.. Repository

' Aggregation relationships
Room "1" *-- "1" RoomNameVO
Room "1" *-- "1" RoomIDVO
Room "1" *-- "1" RoomFloorVO
Room "1" *--left "1" RoomDimensionsVO
Room "1" *--right "1" HouseIDVO
RoomDimensionsVO "1" *-- "1" RoomLengthVO
RoomDimensionsVO "1" *--left "1" RoomWidthVO
RoomDimensionsVO "1" *--up "1" RoomHeightVO

@enduml