@startuml

skinparam ParticipantPadding 50

autonumber
title Use Case - Add Device to Room v5.0 - Main Success Scenario

participant ":AddDeviceToRoomCTRL" as C
participant ":RoomDTOMapper" as RM
participant ":RoomDTO" as RDTO
participant "roomIDVO : RoomIDVO" as RID
participant ":DeviceDTOMapper" as DDM
participant ":DeviceDTO" as DDTO
participant "deviceNameVO : DeviceNameVO" as DN
participant "deviceModelVO : DeviceModelVO" as DM
participant ":DeviceServiceImpl" as DS
participant ":RoomRepositoryMem" as RRM
participant ":DeviceFactoryImpl" as DF
participant "device : Device" as D
participant "deviceStatusVO : DeviceStatusVO" as DStat
participant "deviceIDVO : DeviceIDVO" as DID
participant ":DeviceRepositoryMem" as DRM

/'note over RM : Should include interaction with RoomDTO?'/

[o-> C : addDeviceToRoom(roomDTO, deviceDTO)
activate C

C -> RM : createRoomIDVO(roomDTO)
activate RM

RM -> RDTO : strRoomID = getRoomID()
RM -> RM : uuid = fromString(strRoomID)
RM -> RID ** : create(uuid)
RM --> C : roomIDVO
deactivate RM
|||
C -> DDM : createDeviceName(deviceDTO)
activate DDM

DDM -> DDTO : strDeviceName = getDeviceName()
DDM -> DN ** : create(strDeviceName)
DDM --> C : deviceNameVO
deactivate DDM
C -> DDM : createDeviceModel(deviceDTO)
activate DDM
DDM -> DDTO : strDeviceModel = getDeviceModel()
DDM -> DM ** : create(strDeviceModel)
DDM --> C : deviceModelVO
deactivate DDM

C -> DS : addDevice(deviceNameVO, deviceModelVO, roomIDVO)
activate DS

DS -> RRM : isPresent(roomIDVO)
activate RRM
RRM --> DS : <font color=green>**true**</font>
deactivate RRM

DS -> DF : createDevice(deviceNameVO, deviceModelVO, roomIDVO)
activate DF
DF -> D ** : create(deviceNameVO, deviceModelVO, roomIDVO)
activate D
D -> DStat ** : create(true)
D -> DID ** : create(uuid)
deactivate D
DF --> DS : device
deactivate DF

DS -> DRM : save(device)
activate DRM
DRM -> DRM : validEntity(device)
activate DRM
DRM -> DRM : put(deviceIDVO, device)

deactivate DRM
DRM --> DS : <font color=green>**true**</font>
deactivate DRM

DS --> C : <font color=green>**true**</font>
deactivate DS

[o<-- C : <font color=green>**true**</font>
deactivate C

@enduml