@startuml

title <size: 30> Use Case - Get a List of All Measurements of a Device in a Room in a Given Period v6.0

note "<b>- Only methods related to 'get a list of all measurements \n<b>of a device in a room in a given period' use case are represented.\n<b>- Only the several implementations of LogRepository are representated\n<b>(i.e. RoomRepository and DeviceRepository implementation types were omitted.\n<b>- TimeStampVO and DeltaVO implement ValueObject interface, these relations are abstracted to improve diagram readability" as N1

skinparam linetype ortho

GetLogByDeviceIDAndTimeFrameCTRL ..> DeviceMapper
    DeviceMapper ..> DeviceDTO
    DeviceMapper -- DeviceIDVO : <create>

GetLogByDeviceIDAndTimeFrameCTRL ..> TimeConfigAssembler
    TimeConfigAssembler ..> TimeConfigDTO
    TimeConfigAssembler -- TimeStampVO : <create> >

GetLogByDeviceIDAndTimeFrameCTRL ..> LogService
    LogServiceImpl ..|> LogService
    LogServiceImpl ..> TimeStampVO
    LogServiceImpl ..> LogRepository
    LogServiceImpl ..> RoomRepository
    LogServiceImpl ..> DeviceRepository
    RoomRepository ..|> Repository
    DeviceRepository ..|> Repository

GetLogByDeviceIDAndTimeFrameCTRL ..> LogMapper
LogMapper -- LogDTO : <create>
LogMapper ..> Log

LogRepository .up.|> Repository
LogRepositoryJPA .up.|> LogRepository
    SensorValueFactoryImpl ..|> SensorValueFactory
    LogRepositoryJPA ..> EntityManagerFactory
    LogFactoryImpl .up.|> LogFactory
    LogRepositoryJPA ..> LogAssembler


LogRepositorySpringData .up.|> LogRepository
    LogRepositorySpringData ..> ILogRepositorySpringData
    LogRepositorySpringData ..> LogAssembler

ILogRepositorySpringData ..|> JpaRepository

LogAssembler ..> LogFactory
LogAssembler ..> SensorValueFactory
SensorValueFactoryImpl -- "*" SensorValueObject : <create> >
LogFactoryImpl -- Log : <create> >
LogAssembler ..> LogDataModel

Log "1" -- "1" LogIDVO
Log  -left- "1" SensorValueObject :  > <has>
Log "1" -- "1" SensorIDVO
Log "1" -- "1" DeviceIDVO
Log "1" -- "1" SensorTypeIDVO

Log .right.|> AggregateRoot

DomainID <|.up. DeviceIDVO
DomainID <|.up. LogIDVO
DomainID <|.up. SensorIDVO
DomainID <|.up. SensorTypeIDVO
ValueObject <|.up. SensorValueObject

interface JpaRepository<T>

interface EntityManagerFactory

interface Repository<T> {
    + save(entity : T) : boolean
    + findAll() : Iterable<T>
    + findByID(id : ID) : T
    + isPresent(id : ID) : boolean
}

interface RoomRepository

interface DeviceRepository{
    + findByRoomID(roomID : RoomIDVO) : Iterable<Device>
}

interface LogRepository {

    + findByDeviceIDAndTimeBetween(deviceID : DeviceIDVO, from : TimeStampVO, to : TimeStampVO) : Iterable<Log>
}

class LogRepositoryJPA{
    - logFactory : LogFactory
    - sensorValueFactory : SensorValueFactory
    - entityManagerFactory : EntityManagerFactory

    + LogRepositoryJPA(logFactory : LogFactory, sensorValueFactory : SensorValueFactory, \nentityManagerFactory : EntityManagerFactory)
    - getDataModelFromId(entityManager : EntityManager, logId : LogIDVO) : Optional<LogDataModel>
    + findByDeviceIDAndTimeBetween(deviceID : DeviceIDVO, from : TimeStampVO, to : TimeStampVO) : Iterable<Log>
}

class LogRepositorySpringData{
    - iLogRepositorySpringData : ILogRepositorySpringData
    - logFactory : LogFactory
    - sensorValueFactory : SensorValueFactory

    + LogRepositorySpringData(iLogRepositorySpringDat : ILogRepositorySpringData, logFactory : LogFactory, sensorValueFactory : SensorValueFactory)
    + findByDeviceIDAndTimeBetween(deviceID : DeviceIDVO, from : TimeStampVO, to : TimeStampVO) : Iterable<Log>f
}


interface LogFactory{
    + createLog(logID : LogIDVO, time : LocalDateTime, reading : SensorValueObject<?>, \nsensorID : SensorIDVO, deviceID : DeviceIDVO, sensorTypeID : SensorTypeIDVO) : Log
}

class LogFactoryImpl{
    + createLog(logID : LogIDVO, time : LocalDateTime, reading : SensorValueObject<?>, \nsensorID : SensorIDVO, deviceID : DeviceIDVO, sensorTypeID : SensorTypeIDVO) : Log
}

interface SensorValueFactory{
    + createSensorValue(reading : String, sensorTypeID : SensorTypeIDVO) : SensorValueObject<?>
}

class SensorValueFactoryImpl{
    - configuration : Configuration
    + SensorValueFactoryImpl(path : String)

}


interface LogService {
    + findReadingsFromDeviceInATimePeriod(deviceID : DeviceIDVO, timeConfig : TimeConfig) : List<Log>
}

class LogServiceImpl {
    - logRepository : LogRepository
    - deviceRepository : DeviceRepository
    - roomRepository : RoomRepository

    + LogServiceImpl(logRepository : LogRepository,\n deviceRepository : DeviceRepository, roomRepository : RoomRepository)
    + FindReadingsFromDeviceInATimePeriod(deviceID : DeviceIDVO, initialTimeStamp : TimeStampVO, finalTimeStamp : TimeStampVO) : List<Log>
}

class GetLogByDeviceIDAndTimeFrameCTRL{
    - logService : LogService

    + GetLogByDeviceIDAndTimeFrameCTRL(logService : LogService)

    + getLogByDeviceIDAndTimeFrame(device : DeviceIDVO, time : TimeConfigDTO) : List<LogDTO>
}

class DeviceMapper{
    + createDeviceIDVO(deviceDTO : DeviceDTO) : DeviceIDVO
}

class DeviceDTO{
    - deviceID : String
    - deviceName : String
    - deviceModel : String
    - deviceStatus : String
    - roomID : String

    + getDeviceID() : String
}

class DeviceIDVO {
    - identifier : UUID

    + DeviceIDVO(identifier : UUID)
}

class SensorIDVO {
  - identifier : UUID

    + SensorIDVO(identifier : UUID)
    }

class SensorTypeIDVO {
  - identifier : UUID

    + SensorTypeIDVO(sensorType : String)
    }

class LogIDVO {
  - identifier : UUID

    + LogIDVO(identifier : UUID)
    }

class LogMapper{
    + domainToDTO (log : Log) : LogDTO

    + domainToDTO (logList : List<Log>) : List<LogDTO>
}

class LogDTO{
    - logID : String
    - localDateTime : String
    - reading : String
    - sensorID String
    - deviceID : String
    - sensorTypeID : String
}

class TimeConfigAssembler{
    - TimeConfigAssembler()

    + createInitialTimeStamp(timeConfigDTO : TimeConfigDTO) : TimeStampVO
    + createFinalTimeStamp(timeConfigDTO : TimeConfigDTO) : TimeStampVO
}

class TimeStampVO{
    - timeStamp : LocalDateTime

    + TimeStampVO(localDateTime : LocalDateTime)
}


class TimeConfigDTO{
    - iDate : String
    - iTime : String
    - eDate : String
    -eTime : String
    -deltaMin : String

    + TimeConfigDTO(iDate : String, iTime : String, eDate : String, eTime : String)
}


class LogDataModel {
    - logID : String
    - time : LocalDateTime
    - reading : String
    - sensorID : String
    - deviceID : String
    - sensorTypeID : String

    + LogDataModel()

    + LogDataModel(log : Log)
}

class LogAssembler {
    + toDomain(logFactory : LogFactory, valueFactory : SensorValueFactory, logDataModel : LogDataModel)

    + toDomain(logFactory : LogFactory, valueFactory : SensorValueFactory, \nlogDataModelList : Iterable<LogDataModel>) : Iterable<Log>
}

class Log{
    - logID : LogIDVO
    - readingTime : LocalDateTime
    - reading : SensorValueObject<?>
    - sensorID : SensorIDVO
    - deviceID : DeviceIDVO
    - sensorTypeID : SensorTypeIDVO

    + Log(reading : SensorValueObject<?>, sensorID : SensorIDVO, \ndeviceID : DeviceIDVO, sensorTypeID : SensorTypeIDVO)

    + Log(logID : LogIDVO, readingTime : LocalDateTime, reading SensorValueObject<?>, sensorID : SensorIDVO, \ndeviceID : DeviceIDVO, sensorTypeID : SensorTypeIDVO)

}

interface SensorValueObject<T>
note left: <b>There are 11 implementations of SensorValueObject interface:\nAverage Power Consumption, Dew Point, Energy Consumption, Humidity, Position,\nPower Consumption, Solar Irradiance, Sun Time, Switch, Temperature and Wind.

interface ValueObject<T>{
    + T getValue()
}


interface DomainID {
    + getID() : String
}


interface AggregateRoot {
    + getID() : DomainID
}

interface ILogRepositorySpringData{
    + findByDeviceIDAndTimeBetween(deviceID : String, from : LocalDateTime, to : LocalDateTime)

    }

@enduml