@startuml
title <size: 30> US12 Class Diagram
skinparam linetype ortho

note "<b>Only methods related to\n<b>US12 are represented" as 1
class AddActuatorToDeviceCTRL {
    - house : House
    - commonListOfRooms : CommonListOfRooms
    - commonListOfDevices : CommonListOfDevices
    - catalogue : ActuatorCatalogue
    - room : Room

    + getListOfRooms() : List <RoomDTO>
    + getListOfDevices() : List <DeviceDTO>
    + addActuatorToDevice(actuatorName : String, actuatorType : String, deviceName : String, simHardware : SimHardwareAct)
}

class ListOfActuators {
    - listOfActuators : ArrayList <Actuator>

    + addActuator(actuatorName : String, actuatorType : String, actuatorCatalogue : ActuatorCatalogue, simHardwareAct : SimHardwareAct)
    - isActuatorInList(actuatorName : String) : boolean
    - findActuator (actuatorName : String) : Actuator

}

class ActuatorCatalogue {
    - listOfInstantiableActuators : List<String>

    - areConstructorParametersValid(configuration : Configuration) : boolean
    - areConstructorParametersValid (filePath : String) : boolean
    + getListOfInstantiableActuators() : List<String>
    + createActuator(actuatorName : String, actuatorType : String, simHardwareAct : SimHardwareAct) : Actuator

}

interface Actuator {

    + getName() : String

}

class CommonListOfRooms {
    - house : House
    - roomDTOAndRoomMap : LinkedHashMap<RoomDTO, Room>
    + getListOfRooms() : List<RoomDTO>
    - truncateList(roomDTOAndRoomMap : Map<RoomDTO, Room>) : List<RoomDTO>
    + getRoomByName(roomName : String) : Room
    - refreshMap() : void
}

class CommonListOfDevices {
    - house : House
    - deviceDTOAndDeviceMap : LinkedHashMap<DeviceDTO, Device>
    + getListOfDevices(room : Room) : List<DeviceDTO>
    - refreshMap() : void
    - truncateList(deviceDTOAndDeviceMap : Map<DeviceDTO, Device>) : List<DeviceDTO>
    + getDeviceByName(room : Room, deviceName : String) : Device
}

class RoomDTOMapper {
    + getRoomDTOList(listOfRooms : List<Room>) : LinkedHashMap<RoomDTO, Room>
    + domainToDTO(room : Room) : RoomDTO
}

class RoomDTO{
           - roomName : String
           - houseFloor : int
           - roomWidth : double
           - roomLength : double
           - roomHeight : double
       }

class Device {
    - deviceName : String
    - deviceModel : String
    - location : String
    - status : boolean
    - listOfSensors : ListOfSensors
    - listOfActuators : ListOfActuators
    - deviceFunctionalities : List<String>
    - areDeviceParametersValid(deviceName : String, deviceModel : String, deviceLocation : String) : boolean
    + addActuator(actuatorName : String, actuatorType : String, catalogue : ActuatorCatalogue , simHardwareAct : SimHardwareAct) : boolean

}

class DeviceDTOMapper {
    + domainToDTO(deviceList : List<Device>) : ArrayList<DeviceDTO>
    + getDeviceDTOList(listOfDevices : List<Device>) : LinkedHashMap<DeviceDTO, Device>

}

class DeviceDTO{
           - deviceName : String
           - deviceModel : String
           - location : String
           - status : boolean
           }

       AddActuatorToDeviceCTRL ..> CommonListOfRooms
       AddActuatorToDeviceCTRL ..> Device
       Device --* ListOfActuators : has
       ListOfActuators ..> ActuatorCatalogue
       ActuatorCatalogue -- Actuator : creates >
       CommonListOfRooms ..> RoomDTOMapper
       AddActuatorToDeviceCTRL..> CommonListOfDevices
       CommonListOfDevices ..> DeviceDTOMapper
       DeviceDTOMapper ..> DeviceDTO
       RoomDTOMapper ..> RoomDTO

@enduml