@startuml

title User Story 12 - Main Success Scenario
autonumber
!theme cerulean

participant ":AddActuatorToDeviceCTRL" as C
participant ":CommonListOfRooms" as CU
participant ":CommonListOfDevices" as CD
participant ":Device" as D
participant ":ListOfActuators" as LA
participant ":ActuatorCatalogue" as AC
participant "actuator : Actuator" as A



[o-> C : getListOfRooms()
activate C
C -> CU : getListOfRooms()
activate CU
CU -> CU : refreshMap()
activate CU
deactivate CU
CU -> CU : truncateList(roomDTOAndRoomMap)
activate CU
deactivate CU
CU --> C : roomDtoList
deactivate CU
[o<-- C : roomDtoList
deactivate C
[o-> C : getListOfDevices(roomName)
activate C
C -> CU: getRoomByName(roomName)
activate CU
CU -> CU : refreshMap()
activate CU
deactivate CU
CU --> C : room
deactivate CU
C -> CD : getListOfDevices(room)
activate CD
CD -> CD : refreshMap(room)
activate CD
deactivate CD
CD -> CD : truncateList(deviceDTOAndDeviceMap)
activate CD
deactivate CD
CD --> C : dtoDeviceList
deactivate CD
[o<-- C : dtoDeviceList
deactivate C

[o-> C : getListOfActuatorTypes()
activate C
C -> AC : getListOfInstantiableActuators()
activate AC
C <--AC : listOfInstantiableActuators
deactivate AC
[o<-- C : listOfInstantiableActuators
deactivate C

[o->C : addActuatorToDevice(actuatorName, actuatorType, deviceName, simHardware)
activate C
C -> CD : getDeviceByName(deviceName, room)
activate CD
CD -> CD : refreshMap(room)
activate CD
deactivate CD
CD --> C : device
deactivate CD

C -> D : addActuator(actuatorName, actuatorType, catalogue, simHardwareAct)
activate D
D -> LA : addActuator(actuatorName,actuatorType, catalogue, simHardwareAct)
activate LA

LA -> AC : createActuator(actuatorName, actuatorType, simHardwareAct)
activate AC
AC -> A** : create(actuatorName, simHardwareAct)
AC --> LA : actuator
deactivate AC
LA -> LA : add(actuator)
activate LA
deactivate LA
LA --> D : return true
deactivate LA
D --> C : return true
deactivate D
[o<-- C : return true
deactivate C
@enduml