@startuml

title User Story 12 - Main Success Scenario
autonumber


participant ":AddActuatorToDeviceCTRL" as C
participant ":ActuatorAggregate" as AG
participant ":HouseRepo" as HR
participant ":RoomRepo" as RR
participant ":DeviceRepo" as DR
participant ":ActuatorRepo" as AR
participant ":RoomMapper" as RM
participant ":DeviceMapper" as DM
participant "ActuatorMapper" as AM


[o-> C : houseID : getHouseID()
activate C
C -> HR : houseID : getHouseID()
activate HR
deactivate HR

[o-> C : roomDTOList : getListOfRooms(houseID)
C -> RR : roomList : getRoomList(houseID)
activate RR
deactivate RR
C -> RM : roomDTOList : domainToDto(roomList)
activate RM
deactivate RM


[o-> C : deviceDTOList : getListOfDevices(roomID)
C -> DR : deviceList : getListOfDevices(roomID)
activate DR
deactivate DR
C -> DM : deviceDTOList : domainToDto(deviceList)
activate DM
deactivate DM

[o-> C : actuatorTypeDTOList : getListOfActuatorTypes()
C -> AR : actuatorTypeList : getListOfInstantiableActuators()
activate AR
deactivate AR
C -> AM : actuatorTypeDTOList : domainToDto(actuatorTypeList)
activate AM
deactivate AM

[o->C : boolean : addActuatorToDevice(actuatorName, actuatorType, deviceName)
C -> DR : device : getDeviceByName(deviceName, room)
activate DR
deactivate DR
C -> AG : actuator : addActuatorToDevice(actuatorName, actuatorType, deviceName)
activate AG
deactivate AG
C -> AR : boolean : saveActuator(actuator)
activate AR
deactivate AR
@enduml