@startuml
title <size: 30> US12 Class Diagram
skinparam linetype ortho

note "<b>Only methods related to\n<b>US12 are represented" as 1
class AddActuatorToDeviceCTRL {
    - house : House
    - roomRepo : RoomRepo
    - deviceRepo : DeviceRepo
    - room : Room

    + getListOfRooms() : List <RoomDTO>
    + getListOfDevices() : List <DeviceDTO>
    + addActuatorToDevice(actuatorName : String, actuatorType : String, deviceName : String)
}

class ActuatorRepo {
    - listOfActuators : ArrayList <Actuator>
    + getListOfInstantiableActuators() : ArrayList <actuatorType>

}

class ActuatorAggregate {
    + getListOfInstantiableActuators() : List<String>
    + createActuator(actuatorName : String, actuatorType : String, simHardwareAct : SimHardwareAct) : Actuator
    - areConstructorParametersValid(configuration : Configuration) : boolean
    - areConstructorParametersValid (filePath : String) : boolean

}

interface Actuator {

    + getName() : String

}

class RoomRepo {
    + getRoomList() : List<RoomDTO>
    + getRoomByID(roomId : String) : Room
}

class DeviceRepo {
    + getListOfDevices(room : Room) : List<Device>
    + getDeviceByName(room : Room, deviceName : String) : Device
}

class RoomDTOMapper {
    + domainToDTO(roomList : ArrayList) : ArrayList <RoomDTO>
}

class RoomDTO{
           - roomName : String
           - houseFloor : int
           - roomWidth : double
           - roomLength : double
           - roomHeight : double
       }

class Device {
    - deviceName : String
    - deviceModel : String
    - location : String
    - status : boolean
    - listOfSensors : ListOfSensors
    - listOfActuators : ListOfActuators
    - deviceFunctionalities : List<String>
    + addActuator(actuatorName : String, actuatorType : String, catalogue : ActuatorCatalogue , simHardwareAct : SimHardwareAct) : boolean
    - areDeviceParametersValid(deviceName : String, deviceModel : String, deviceLocation : String) : boolean

}

class DeviceDTOMapper {
    + domainToDTO(deviceList : List<Device>) : ArrayList<DeviceDTO>

}

class DeviceDTO{
           - deviceName : String
           - deviceModel : String
           - location : String
           - status : boolean
           }

       AddActuatorToDeviceCTRL ..> RoomRepo
       AddActuatorToDeviceCTRL ..> Device
       Device "1" *-- "1" ActuatorRepo
       ActuatorRepo <.. ActuatorAggregate
       AddActuatorToDeviceCTRL ..> RoomDTOMapper
       AddActuatorToDeviceCTRL..> DeviceRepo
       AddActuatorToDeviceCTRL ..> DeviceDTOMapper
       DeviceDTOMapper ..> DeviceDTO
       RoomDTOMapper ..> RoomDTO

@enduml