@startuml

title <size: 30> US07 Class Diagram
note "<b>Only methods related to\n<b>US12 are represented" as N1
skinparam linetype ortho

       AddActuatorToDeviceCTRL ..> DeviceService
       AddActuatorToDeviceCTRL ..> ActuatorTypeService
       AddActuatorToDeviceCTRL ..> ActuatorMapper
       AddActuatorToDeviceCTRL ..> ActuatorTypeMapper
       AddActuatorToDeviceCTRL ..> DeviceMapper
       AddActuatorToDeviceCTRL ..> ActuatorService
       ActuatorService ..> ActuatorRepository
       ActuatorService ..> ActuatorFactory
       ActuatorTypeService ..> ActuatorTypeRepository
       ActuatorFactory -- Actuator : creates >
       DeviceMapper ..> DeviceDTO
       DeviceMapper -- DeviceIDVO : creates >
       ActuatorMapper ..> ActuatorDTO
       ActuatorMapper -- ActuatorNameVO : creates >
       ActuatorTypeMapper ..> ActuatorTypeDTO
       ActuatorTypeMapper -- ActuatorTypeIDVO : creates >
       DeviceService ..> DeviceRepository
       DeviceRepository ..|> Repository
       ActuatorRepository ..|> Repository
       ActuatorTypeRepository ..|> Repository
       ActuatorMapper -- IntegerSettingsVO : creates >
       ActuatorMapper -- DecimalSettingsVO : creates >
       IntegerSettingsVO ..|> Settings
       DecimalSettingsVO ..|> Settings
       ActuatorNameVO ..|> ValueObject
       ActuatorTypeIDVO ..|> ValueObject
       DeviceIDVO ..|> ValueObject



    class AddActuatorToDeviceCTRL{
        -actuatorService: ActuatorService
        -actuatorTypeService: ActuatorTypeService
        -deviceService: DeviceService
        +AddActuatorToDeviceCTRL(actuatorService, actuatorTypeService, deviceService)
        +getListOfActuatorTypes(): List<ActuatorTypeDTO>
        +addActuatorToDevice(sensorDTO, sensorTypeDTO, deviceDTO): boolean
    }

    class ActuatorTypeService{
        -actuatorTypeRepository: ActuatorTypeRepository
        -actuatorTypeFactory: ActuatorTypeFactory
        +ActuatorTypeService(actuatorTypeRepository, actuatorTypeFactory)
        +getListOfActuatorTypes(): Iterable<ActuatorType>
    }

    class ActuatorTypeRepository{
        -actuatorTypes: Map<ActuatorTypeIDVO, ActuatorType>
        +findAll(): Iterable<ActuatorType>
    }

    class ActuatorService{
        -actuatorRepository: ActuatorRepository
        -actuatorFactory: ActuatorFactory
        +ActuatorService(actuatorFactory, actuatorRepository)
        +createActuator(actuatorNameVO, deviceIDVO, actuatorTypeIDVO): Actuator
        +saveActuator(actuator: Actuator): boolean
    }

    class ActuatorRepository{
        -actuatorMap : Map<ActuatorIDVO, Actuator>
        +save(actuator : Actuator): boolean
    }

    class ActuatorFactory{
        -filePath: String
        -configuration: Configuration
        +createActuator(actuatorNameVO, actuatorTypeIDVO, deviceIDVO): Sensor
    }

    class ActuatorMapper{
        +ActuatorMapper()
        +createActuatorNameVO(sensorDTO): ActuatorNameVO
    }

    class ActuatorTypeMapper{
        +ActuatorTypeMapper()
        +domainToDTO(actuatorTypeList): List<ActuatorTypeDTO>
        +createActuatorTypeIDVO(actuatorTypeDTO): ActuatorTypeIDVO
    }

    class DeviceMapper{
        +DeviceMapper()
        +createDeviceIDVO(deviceDTO): DeviceIDVO
    }

    class DeviceService{
        -deviceRepository: DeviceRepository
        -deviceFactory: DeviceFactory
        +DeviceService(deviceRepository, deviceFactory)
        +isActive(deviceIDVO): boolean
    }

    class DeviceRepository{
        -DATA: Map<DeviceIDVO, Device>
        +findById(deviceIDVO): Device
    }

    class ActuatorDTO{
        -actuatorName: String
        -actuatorID: String
        -deviceID: String
        -actuatorType: String
        +getActuatorName(): String
    }

    class ActuatorTypeDTO{
        -actuatorTypeID: String
        +getActuatorTypeID(): String
    }

    class DeviceDTO{
        -deviceID: String
        -deviceName: String
        -deviceModel: String
        -roomID: String
        -deviceStatus: boolean
        +getDeviceID(): String
    }

    interface Repository{
        + findAll() : List<T>
        + findByID(id : ID) : T
        + isPresent(id : ID) : boolean
        + save(ent : T) : boolean
    }

    class ActuatorNameVO{
            -actuatorrName: String
            +ActuatorNameVO(actuatorName)
        }

        class ActuatorTypeIDVO{
            -actuatorTypeID: String
            +ActuatorTypeIDVO(actuatorTypeID)
        }

        class DeviceIDVO{
            -deviceID: UUID
            +DeviceIDVO(deviceID)
        }

        class IntegerSettingsVO{
        -lowerLimit: int
        -upperLimit : int
        -validLimits(lowerLimit, upperLimit): boolean
        +getValue(): int[]
        }

        class DecimalSettingsVO{
        -lowerLimit: double
        -upperLimit : double
        -precision : double
        -validSettings(lowerLimit, upperLimit, precision): boolean
        -countDecimalPlaces(value : double): int
        +getValue(): double[]
        }


    interface Actuator{

    }

    interface Settings{

    }

    interface ValueObject{
    getValue(): T
    }




@enduml