@startuml
title <size: 30> US09 Class Diagram v4.2
note "<b>Only methods related to\n<b>US09 are represented" as N1
skinparam linetype ortho

class GetDevicesByFunctionalityCTRL {
    - deviceService : DeviceService
    - sensorService : SensorService
    - deviceMapper : DeviceMapper
    + getListOfDevicesByFunctionality() : Map<str, DeviceDTO>
}

class SensorService {
    - sensorRepository : SensorRepository
    + SensorService (sensorRepository : SensorRepository)
    + getListOfDeviceIDsByFunctionality() : Map<str:DeviceIDVO>
}

class SensorRepository {
    - data : Hashmap<SensorIDVO,Sensor>
    + findAll() : Iterable<Sensor>
}

class Sensor {
    - sensorTypeID : SensorTypeIDVO
    - deviceIDVO : DeviceIDVO
    + getSensorID().getID() : String
    + getDeviceIDVO() : DeviceIDVO
}

class ActuatorService {
    - actuatorRepository : actuatorRepository
    + actuatorService (actuatorRepository : atuatorRepository)
    + getListOfDeviceIDsByFunctionality() : Map<str:DeviceIDVO>
}

class ActuatorRepository {
    - data : Hashmap<ActuatorIDVO,Actuator>
    + findAll() : Iterable<Actuator>
}

class Actuator {
    - actuatorTypeID : actuatorTypeIDVO
    - deviceIDVO : DeviceIDVO
    + getActuatorID().getID() : String
    + getDeviceIDVO() : DeviceIDVO
}

class DeviceService {
    - deviceRepository : Device DeviceRepository
    + DeviceService (deviceRepository : DeviceRepository)
    + getDevices(sensorTypeIDstrToDeviceIDVO) : Map<str:Device>
}

class DeviceRepository {
    - data : Hashmap<DeviceIDVO,Device>
    + findByID (DeviceIDVO) : Device
}

class DeviceMapper {
    + domainToDTO (sensorTypeIDstrToDeviceMap) : sensorTypeIDstrToDeviceDTOMap
}

class DeviceDTO {
}

interface Repository {
    + findAll() : Iterable<T>
    + findByID (id : DomainID) : T
}

SensorService <|.. GetDevicesByFunctionalityCTRL
ActuatorService <|.. GetDevicesByFunctionalityCTRL
DeviceService <|.. GetDevicesByFunctionalityCTRL
DeviceMapper o.. GetDevicesByFunctionalityCTRL

SensorRepository <|.. SensorService
ActuatorRepository <|.. ActuatorService
DeviceRepository <|.. DeviceService

Sensor o.. SensorService
Actuator o.. ActuatorService

Repository <.. SensorRepository
Repository <.. ActuatorRepository
Repository <.. DeviceRepository

DeviceDTO *.. DeviceMapper

@enduml

