@startuml
title <size: 30> Switch Sensor v6.0\n<size: 25>Development View

note "<b>Only methods related to \n<b>HumiditySensor are represented" as 1

skinparam linetype ortho

interface Sensor {
    + getSensorTypeID() : SensorTypeIDVO;
    + getDeviceID() : DeviceIDVO;
    + getSensorName() : SensorNameVO;
}


interface ValueObject<T> {
    + getValue() : T
}

class SensorNameVO{
    - sensorName : String
    + getValue() : String
}

class DeviceIDVO{
    - deviceID : UUID
    + getID() : String
}

class SensorTypeIDVO{
    - sensorTypeID : String
    + getID() : String
}

class SensorIDVO{
    - identifier : UUID
    + getValue() : String
}


class SwitchSensor{
    - sensorName : SensorNameVO
    - deviceID : DeviceIDVO
    - sensorType : SensorTypeIDVO
    - sensorID : SensorIDVO

    + getReading(simHardware : SimHardware) : ValueObject<Integer>
}

class SwitchValue{
    - switchValue : String

    + getValue() : String
    - isReadingValid(switchValue : String) : boolean
}

class SimHardware{
    + getValue() : String
}

interface SensorExternalServices {
+getValue() : String
}

interface AggregateRoot {
    +getID() : DomainID
}

Sensor <|..left SwitchSensor
SimHardware <.. SwitchSensor

SensorNameVO <.. SwitchSensor
SensorExternalServices <|..down SimHardware
SensorIDVO ..> SwitchSensor
SwitchValue <..right SwitchSensor
SensorTypeIDVO <.. SwitchSensor
DeviceIDVO <.. SwitchSensor

ValueObject <|.. SensorNameVO
DomainID  <|.. SensorIDVO
DomainID  <|.. SensorTypeIDVO
DomainID  <|.. DeviceIDVO

ValueObject <|.. SwitchValue
Sensor -up-|> AggregateRoot

@enduml