 @startuml
title User Story 6 - Main Success Scenario

autonumber

participant ":GetListOfDevicesCTRL" as C
participant ":CommonListOfDevices" as CD
participant ":DeviceRepo" as DR
participant ":DeviceDTOMapper" as DM


[o-> C : getListOfDevices(roomID)
activate C
C -> C: getRoomByName(roomID)
activate C
deactivate C
C -> DR : getListOfDevices(roomID)
activate DR
DR -> DR : getIdDeviceList(roomID)
activate DR
deactivate DR
loop for each device in device list
DR -> DR : cloneIdList()
activate DR
deactivate DR
end loop
DR --> C : IdDeviceList
deactivate DR
C -> DM : getIdDeviceDTOList(idDeviceList)
activate DM
loop for each device in device list
DM -> DM : idDeviceDTOList = domainToDTO(idDevice)
activate DM
deactivate DM
end loop
DM --> C : dtoIdDeviceList
deactivate DM
[o<-- C : dtoIdDeviceList
deactivate C

@enduml