@startuml
       title <size: 30> US06 Class Diagram

note "<b>Only methods related to\n<b>US06 are represented" as N1
skinparam linetype ortho

       class CommonListOfRooms{
           - house : House
           -roomDTOAndRoomMap : LinkedHashMap<RoomDTO, Room>

           + getListOfRooms() : List<RoomDTO>
           - truncateList(roomDTOAndRoomMap : Map<RoomDTO, Room>) : List<RoomDTO>
           - refreshMap() : void
           + getRoomByName(roomName : String) : Room
       }

       class RoomDTO{
           - roomName :String
           - houseFloor : int
           - roomWidth : double
           - roomLength : double
           - roomHeight : double
       }

       class RoomDTOMapper{
           + getRoomDTOList(listOfRooms : List<Room>) : LinkedHashMap<RoomDTO, Room>
           + domainToDTO(room : Room) : RoomDTO
       }

       class House {
           - houseName: String
           - gps : GPS
           - address : Address
           - listOfRooms : ListOfRooms

           + getListOfRooms() : List<Room>
       }

       class ListOfRooms{
           - roomList : ArrayList<Room>
           + getRoomList () : List<Room>
       }

       class Room {
           - roomName: String
           - houseFloor : int
           - dimensions : RoomDimensions
           - deviceList : ListOfDevices
           + getListOfDevices() : List<Device>
       }

       class ListOfDevices{
           - deviceList : ArrayList<Device>
           + getDeviceList() : List<Device>
       }

       class CommonListOfDevices{
           - house : House
           - deviceDTOAndDeviceMap : LinkedHashMap<DeviceDTO, Device>

           - truncateList(deviceDTOAndDeviceMap : Map<DeviceDTO, Device>) : List<DeviceDTO>
           - refreshMap(room : Room) : void
           + getListOfDevices(room : Room) : ArrayList<Device>

       }

       class DeviceDTOMapper{
           + domainToDTO(device : Device) : DeviceDTO
              + getDeviceDTOList(listOfDevices : List<Device>) : LinkedHashMap<DeviceDTO, Device>
       }

       class GetListOfDevicesFromRoomCTRL{
           - house : House
           - commonListOfRooms : CommonListOfRooms
           - commonListOfDevices : CommonListOfDevices

           + getListOfRooms() : List<RoomDTO>
           + getListOfDevices(roomName : String) : List<DeviceDTO>

       }

       class DeviceDTO{
           - deviceName : String
           - deviceModel : String
           - location : String
           - status : boolean
           }



       GetListOfDevicesFromRoomCTRL ..> CommonListOfRooms
       CommonListOfRooms ..> RoomDTOMapper
       RoomDTOMapper ..> RoomDTO
       CommonListOfRooms -down.> House
       House "1" *-- "1" ListOfRooms
       CommonListOfDevices ..> Room
       Room "1" *-- "1" ListOfDevices
       GetListOfDevicesFromRoomCTRL ..> CommonListOfDevices
       CommonListOfDevices ..> DeviceDTOMapper
       DeviceDTOMapper ..> DeviceDTO

       @enduml