 @startuml
title User Story 6 - Main Success Scenario

autonumber

participant ":GetListOfDevicesCTRL" as C
participant ":CommonListOfRooms" as CU
participant ":CommonListOfDevices" as CD
participant ":Room" as R
participant ":ListOfDevices" as LD
participant ":DeviceDTOMapper" as DM



[o-> C : getListOfRooms()
activate C
C -> CU : getListOfRooms()
activate CU
CU -> CU : refreshMap()
activate CU
deactivate CU

CU -> CU : truncateList(roomDTOAndRoomMap)
activate CU
deactivate CU
CU --> C : roomDtoList
deactivate CU
[o<-- C : roomDtoList
deactivate C

[o-> C : getListOfDevices(roomName)
activate C
C -> CU: getRoomByName(roomName)
activate CU
CU -> CU : refreshMap()
activate CU
deactivate CU
CU --> C : room
deactivate CU
C -> CD : getListOfDevices(room)
activate CD

CD -> R : getListOfDevices()
activate R
R -> LD : getListOfDevices()
activate LD
LD -> LD : getDeviceList()
activate LD
deactivate LD
LD --> R : deviceList
deactivate LD
R --> CD : deviceList
deactivate R
CD -> DM : getDeviceDTOList(deviceList)
activate DM
loop for each device in device list
DM -> DM : DeviceDTO = domainToDTO(device)
activate DM
deactivate DM
DM -> DM : put(DeviceDTO, device)
activate DM
deactivate DM
end loop
DM --> CD : deviceDTOAndDeviceMap
deactivate DM
CD -> CD : truncateList(deviceDTOAndDeviceMap)
activate CD
deactivate CD
CD --> C : dtoDeviceList
deactivate CD
[o<-- C : dtoDeviceList
deactivate C

@enduml