@startuml
autonumber
title User Story 2 - Main Success Scenario
participant ":AddRoomCTRL" as C
participant ":RoomMapper" as Rm
participant ":HouseService" as Hs
participant ":HouseRepo" as Hr
participant ":RoomService" as Rs
participant ":RoomFactory" as fR
participant "room : Room" as R
participant ":RoomRepo" as rR
skinparam ParticipantPadding 50

[o-> C : addRoom(roomDTO)
activate C
C -> Rm : roomNameVO = createRoomNameVO(roomDTO)
activate Rm
C -> Rm : roomFloorVO = createRoomFloorVO(roomDTO)
C -> Rm : roomDimensionsVO = createRoomDimensionsVO(roomDTO)
deactivate Rm
C -> Hs : getHouseIDVO()
activate Hs
Hs -> Hr : getHouseIDVO()
deactivate Hs
activate Hr
C <-- Hr : houseIDVO
deactivate Hr
C -> Rs : createRoom(roomNameVO, roomFloorVO, \nroomDimensionsVO, houseIDVO)
activate Rs
Rs -> fR : createRoom(roomNameVO, roomFloorVO, \nroomDimensionsVO, houseIDVO)
deactivate Rs

activate fR
fR -> R** : newRoom(roomNameVO, roomFloorVO, \nroomDimensionsVO, houseIDVO)
C <-- fR : room
deactivate fR

C -> Rs : saveRoom(room)
activate Rs
Rs -> rR : save(room)
deactivate Rs
activate rR
C <-- rR : true
deactivate rR
[o<-- C : Room Added!
deactivate C


@enduml