@startuml
title Use case Deactivate Device - v5.0  - Main Success Scenario
autonumber

participant ":DeactivateDeviceCTLR" as C
participant ":DeviceMapper" as DVM
participant ":DeviceDTO" as DTO
participant "DeviceIDVO :deviceIDVO" as DVO
participant ":DeviceService" as DS
participant ":DeviceRepository" as DR
participant "dev:Device" as D
participant "deviceStatus:DeviceStatus" as DVS


[o-> C : deactivateDevice(DeviceDTO)
activate C
C -> DVM : getDeviceIDVO(DeviceDTO)
activate DVM
DVM -> DTO : getDeviceID()
activate DTO
DTO --> DVM : deviceID
deactivate DTO
DVM -> DVO** : create(deviceID)
DVM --> C : deviceIDVO
deactivate DVM
C -> DS : deactivateDevice(DeviceIDVO)
activate DS
DS -> DR : findByID(DeviceIDVO)
activate DR
DR --> DS : dev
deactivate DR
DS -> D : isActive()
activate D
D --> DS : true
deactivate D
DS -> D : deactivateDevice()
activate D
D -> DVS** : create(false)
D --> DS : true
deactivate D
DS --> C : device
deactivate DS
[o<-- C : true
deactivate C
@enduml