@startuml
title <size: 30> Use case Deactivate Device - v5.0
note "<b>Only methods related to\n<b>use case Deactivate Device are represented" as N1
skinparam linetype ortho

class DeactivateDeviceCTRL {
    - deviceService : DeviceServiceImpl
    + DeactivateDeviceCTRL(DeviceService)
    + deactivateDevice(DeviceDTO) : boolean
}

class DeviceDTOMapper {
    + DeviceDTOMapper()
    + getDeviceIDVO(DeviceDTO) : DeviceIDVO
}

class DeviceDTO{
- String deviceID
- String deviceName
- String deviceModel
- String deviceStatus
- String roomID

+ DeviceDTO(Device)
+ getDeviceID() : String
+ getDeviceName() : String
+ getDeviceModel() : String
+ getDeviceStatus() : String
+ getDeviceRoomID() : String
}

interface DomainID{
    + getID() : String
}

class DeviceIDVO {
    + DeviceIDVO(String)
}

class DeviceServiceImpl {
    - factoryDevice : FactoryDevice
    - repositoryDevice : RepositoryDevice
    - roomRepository : RoomRepository
    + DeviceServiceImpl(FactoryDevice,RepositoryDevice,RoomRepository)
}

interface DeviceService {
    + deactivateDevice(DeviceIDVO) : boolean
}


interface Repository<ID extends DomainID, T extends DomainEntity> {
    + findAll() : List<T>
    + findByID(id : ID) : T
    + isPresent(id : ID) : boolean
    + save(ent : T) : boolean
}

interface DeviceRepository<DeviceIDVO, Device> {

}
class DeviceRepositoryImpl {
     - deviceIdAndDeviceMap : Map<DeviceID,Device>
     + findByID(deviceID : DeviceIDVO) : Device
}

interface ValueObject<T> {
     + getValue() : T
}

class DeviceStatusVO {
    - status : boolean
    + DeviceStatusVO(status : boolean)
    + getValue() : Boolean

}

interface DomainEntity {
     + getId() : DomainID
}

class Device {
   - deviceID : DeviceIDVO
   - roomID : RoomIDVO
   - deviceName : DeviceNameVO
   - model : DeviceModelVO
   - deviceState : DeviceStatusVO
   + Device(roomID : RoomIDVO, deviceName : DeviceNameVO, model : DeviceModelVO)
   + deactivateDevice() : boolean
   + isActive() : boolean
}



DeactivateDeviceCTRL ..> DeviceService
DeactivateDeviceCTRL ..> DeviceDTOMapper
DeviceServiceImpl ..> DeviceRepository

DeviceDTOMapper ..> DeviceDTO

DomainID <|..up DeviceIDVO

DeviceRepository o-- Device
Repository <|.. DeviceRepository
DeviceRepository <|.. DeviceRepositoryImpl


Device ..up|> DomainEntity

Device *-- DeviceIDVO
Device *-- DeviceStatusVO
DeviceService <|.. DeviceServiceImpl


ValueObject <|..up DeviceStatusVO

@enduml
