@startuml

note "<b>Only methods related to\n<b>US07 are represented" as N1
title <size: 30> US07 Class Diagram

class House
class RoomDTO
class Room
class DeviceDTO
class SensorTypeOptions
class CommonListOfRooms
class RoomDTOMapper
class CommonDeviceListCTRL
class ListOfDevices
class Device
class DeviceDTOMapper
class ListOfSensors
class HumiditySensor implements Sensor
class TemperatureSensor implements Sensor


class AddSensorToDeviceCTRL {
    - house: House
    + getListOfRooms(): ArrayList<RoomDTO>
    + listOfDevicesInARoom(roomDTO: RoomDTO): ArrayList<DeviceDTO>
    + getAvailableSensorTypes(): ArrayList<SensorTypeOptions>
    + addSensorToDevice(roomDTO: RoomDTO, deviceDto: DeviceDTO, nameSensor: String, sensorType: SensorTypeOptions): int
    - getRoomFromDto(roomDTO: RoomDTO): Room
    - getDeviceFromDto(room: Room, deviceDTO: DeviceDTO): Device
}

class CommonListOfRooms {
    - house: House

    + getListOfRooms(): ArrayList<Room>
}

class RoomDTOMapper {
    + domainToDTO(room: Room): RoomDTO
    + getRoomDTOList(list: ArrayList<Room>): ArrayList<RoomDTO>
    + dtoToDomain(roomDTO: RoomDTO, myhouse: House): Room
}
class DeviceDTOMapper {
  + domainToDTO(device: Device): DeviceDTO
  + domainToDTO(list: ArrayList<Device>): ArrayList<DeviceDTO>
  + dtoToDomain(room: Room, deviceDTO: DeviceDTO): Device
}

class CommonDeviceListCTRL {
  - house: House

  + getListOfDevices(room: Room): ArrayList<Device>
}

class Device {
  - deviceName: String
  - deviceModel: String
  - deviceLocation: String
  - status: boolean
  - listOfSensors: ListOfSensors

}

class House {
  - houseName: String
  - gps: GPS
  - address: Address
  - listOfRooms: ListOfRooms
}

interface Sensor {

}

class ListOfRooms {
  - roomList: ArrayList<Room>

}

class ListOfDevices {
  - deviceList: ArrayList<Device>


}

class Room {
  - roomName: String
  - houseFloor: int
  - dimensions: RoomDimensions
  - deviceList: ListOfDevices

}

class ListOfSensors {
  - listOfSensors: ArrayList<Sensor>
  + ListOfSensors()
  + addSensor(sensorName: String, sensorType: SensorTypeOptions): int
  - isSensorInList(sensorName: String): boolean

}


class HumiditySensor {
  - sensorName: String
  - TYPE: SensorTypeOptions
  - reading: double
  - log: ArrayList<String>

}

enum SensorTypeOptions {

}

class TemperatureSensor {
  - sensorName: String
  - TYPE: SensorTypeOptions
  - reading: double
  - log: ArrayList<String>
}

class RoomDTO {
  - roomName: String
  - houseFloor: int
  - roomWidth: double
  - roomLength: double
  - roomHeight: double
}

class DeviceDTO {
  - deviceName: String
  - deviceModel: String
  - location: String

}



AddSensorToDeviceCTRL  -right..>  RoomDTOMapper
RoomDTOMapper -up.> RoomDTO
AddSensorToDeviceCTRL  -up.> DeviceDTOMapper
DeviceDTOMapper -right..> DeviceDTO
AddSensorToDeviceCTRL -..> CommonDeviceListCTRL
CommonDeviceListCTRL -right..> House
AddSensorToDeviceCTRL  -up.>  CommonListOfRooms
AddSensorToDeviceCTRL ..>  House
House "1" *--right "1" ListOfRooms
ListOfRooms "1" o--right "*" Room
Room "1" *-- "1" ListOfDevices
ListOfDevices "1" o--left "*" Device
Device "1" *--left "1" ListOfSensors
ListOfSensors "1" o--left "*" Sensor
TemperatureSensor "*"--down "1" SensorTypeOptions
HumiditySensor "*"--"1" SensorTypeOptions







@enduml