@startuml

autonumber

title User Story 1 - Main Success Scenario

participant ":ConfigureLocationCTRL" as C
participant ":House" as H
participant ":FactoryLocation" as F
participant "address : Address" as A
participant "gps : GPS" as G


skinparam ParticipantPadding 50




[o-> C : configureLocation(doorReference,\nbuildingNumber, streetName, city, \ncountry, zipCode, latitude, longitude)
activate C

C -> H : configureLocation(doorReference, buildingNumber,\nstreetName, city, country,\nzipCode, latitude, longitude, factoryLocation)
activate H

H -> F : createAddress(doorReference, buildingNumber,\nstreetName, city, country, zipCode)
activate F




F -> A** : create(doorReference, buildingNumber,\nstreetName, city, country, zipCode)

F --> H : address



deactivate F

H -> F : createGPS(latitude, longitude)

activate F
F -> G** : create(latitude, longitude)


F --> H : gps
deactivate F

H --> C : return true
deactivate H

[o<-- C : return true
deactivate C

|||
@endumll