@startuml
!theme cerulean
autonumber

title User Story 1 - Main Success Scenario

participant ":ConfigureLocationCTRL" as C
participant ":House" as H
participant "implFactoryLocation:FactoryLocation" as F
participant "address:Address" as A
participant "gps:GPS" as G


skinparam ParticipantPadding 50




[o-> C : configureLocation(doorReference,buildingNumber,\nstreetName,city,country,\nzipCode,latitude,longitude)
activate C

C -> H : configureLocation(doorReference,buildingNumber,\nstreetName,city,country,\nzipCode,latitude,longitude, factoryLocation)
activate H

H -> F : createAddress(doorReference,buildingNumber,\nstreetName,city,country,\nzipCode)
activate F




F -> A** : <create>

F --> H : address



deactivate F

H -> F : createGPS(latitude,longitude)

activate F
F -> G** : <create>


F --> H : gps
deactivate F

H --> C : return true
deactivate H

[o<-- C : return true
deactivate C

|||
@endumll