@startuml

title <size: 30> US01 Class Diagram

note "<b>Only methods related to\n<b>US01 are represented" as N1

skinparam linetype ortho

class ConfigureLocationCtrl {
- houseRepository: HouseRepository
- house : House
+ ConfigureLocationCtrl(houseRepository : HouseRepository)
- getById(id : HouseId) : House
+ configureLocation(address : Address, gps : GPS) : boolean
}

class HouseRepository {
- houseMap : Map<HouseId, House>
+ find(id : HouseId) : House
}

class House {
- id : HouseId
- location : Location
+ configureLocation(address : Address, gps : GPS) : boolean
}

class HouseId {
- id : String
+ getId() : String
}

class Location {
- address : Address
- gps : GPS
+ Location(address : Address, gps : GPS)
+ getAddress() : Address
+ getGps() : GPS
}

class Address {
- doorReference : String
- buildingNumber : String
- streetName : String
- city : String
- country : String
- zipCode : String
+ Address(doorReference : String, buildingNumber : String, \n streetName : String, city : String,\n country : String, zipCode : String)
+ getDoorReference() : String
+ getBuildingNumber() : String
+ getStreetName() : String
+ getCity() : String
+ getCountry() : String
+ getZipCode() : String
}

class GPS {
- latitude : double
- longitude : double
+ GPS(latitude : double, longitude : double)
+ getLatitude() : double
+ getLongitude() : double
}

class FactoryLocation {
+ createLocation(address : Address, gps : GPS) : Location
}

ConfigureLocationCtrl -up.> HouseRepository
ConfigureLocationCtrl -right.> House
House -up.> HouseId
House "1" *---right "1" Location
House -down.> FactoryLocation : <uses>
Location "1" *---right "1" Address
Location "1" *---left "1" GPS
FactoryLocation -down.> Location : <creates>

@enduml