@startuml

autonumber

title User Story 1 - Main Success Scenario

participant ":ConfigureLocationCTRL" as C
participant ":HouseMapper" as HM
participant ":HouseService" as HS
participant ":HouseRepository" as HR
participant ":House" as H

[o-> C : updateLocation(locationDTO)
activate C
C -> HM : locationVO : mapToLocationVO(locationDTO)
C -> HS : updateLocation(locationVO)
activate HS
HS -> HR : house : getFirstHouse()
HS -> H : configureLocation(locationVO)
activate H
H -> H : configureLocation(locationVO)
activate H
deactivate H

H --> HS : **true**
deactivate H

HS --> C : **true**
deactivate HS

[o<-- C : **true**
deactivate C
@enduml