@startuml

title <size: 30> Use Case - Get Maximum Instantaneous Temperature Difference in a Given Period v6.0

note "<b>- Only methods related to 'get maximum instantaneous temperature \n<b>difference in a given period' use case are represented.\n<b>- Only the several implementations of LogRepository are representated\n<b>(i.e. RoomRepository and DeviceRepository implementation types were omitted.\n<b>- TimeStampVO and DeltaVO implement ValueObject interface, these relations are abstracted to improve diagram readability" as N1

skinparam linetype ortho

GetMaxInstantaneousTemperatureDifferenceCTRL ..> DeviceMapper
    DeviceMapper ..> DeviceDTO
    DeviceMapper -- DeviceIDVO : <create> >

GetMaxInstantaneousTemperatureDifferenceCTRL .up.> TimeConfigAssembler
    TimeConfigAssembler .up.> TimeConfigDTO
    TimeConfigAssembler -- TimeStampVO : <create> >
    TimeConfigAssembler -- DeltaVO : <create> >

GetMaxInstantaneousTemperatureDifferenceCTRL ..> LogService
    LogServiceImpl ..|> LogService
    LogServiceImpl .up.> TimeStampVO
    LogServiceImpl .up.> DeltaVO
    LogServiceImpl ..> LogRepository
    LogServiceImpl .up.> RoomRepository
    LogServiceImpl .right.> DeviceRepository
    RoomRepository .right.|> Repository
    DeviceRepository .right.|> Repository

LogRepository .up.|> Repository
LogRepositoryJPA .up.|> LogRepository
    SensorValueFactoryImpl ..|> SensorValueFactory
    LogRepositoryJPA ..> EntityManagerFactory
    LogFactoryImpl .up.|> LogFactory
    LogRepositoryJPA ..> LogAssembler


LogRepositorySpringData .up.|> LogRepository
    LogRepositorySpringData ..> ILogRepositorySpringData
    LogRepositorySpringData ..> LogAssembler

ILogRepositorySpringData ..|> JpaRepository

LogAssembler ..> LogFactory
LogAssembler ..> SensorValueFactory
TemperatureValue ....|> SensorValueObject
SensorValueFactoryImpl -- TemperatureValue : <create> >
LogFactoryImpl -- Log : <create> >
LogAssembler ..> LogDataModel

Log "1" -- "1" LogIDVO
Log  -left- "1" SensorValueObject :  > <has>
Log "1" -- "1" SensorIDVO
Log "1" -- "1" DeviceIDVO
Log "1" -- "1" SensorTypeIDVO

Log ...|> AggregateRoot

DomainID <|.up. DeviceIDVO
DomainID <|.up. LogIDVO
DomainID <|.up. SensorIDVO
DomainID <|.up. SensorTypeIDVO
ValueObject <|.up. SensorValueObject

interface JpaRepository<T>

interface EntityManagerFactory

interface Repository<T> {
    + save(entity : T) : boolean
    + findAll() : Iterable<T>
    + findByID(ID : DomainID) : T
    + isPresent(ID : DomainID) : boolean
}

interface RoomRepository
interface DeviceRepository{
    + findByRoomID(roomID : RoomIDVO) : Iterable<Device>
}

interface LogRepository {

    + getDeviceTemperatureLogs(deviceID : DeviceIDVO, sensorType : String, start : TimeStampVO, end : TimeStampVO) : Iterable<Log>

}

class LogRepositoryJPA{
    - logFactory : LogFactory
    - sensorValueFactory : SensorValueFactory
    - entityManagerFactory : EntityManagerFactory

    + LogRepositoryJPA(logFactory : LogFactory, sensorValueFactory : SensorValueFactory, \nentityManagerFactory : EntityManagerFactory)
    - getDataModelFromId(entityManager : EntityManager, logId : LogIDVO) : Optional<LogDataModel>
    + getDeviceTemperatureLogs(deviceID : DeviceIDVO, sensorType : String, start : TimeStampVO, end : TimeStampVO) : Iterable<Log>}

class LogRepositorySpringData{
    - iLogRepositorySpringData : ILogRepositorySpringData
    - logFactory : LogFactory
    - sensorValueFactory : SensorValueFactory

    + LogRepositorySpringData(iLogRepositorySpringDat : ILogRepositorySpringData, logFactory : LogFactory, sensorValueFactory : SensorValueFactory)
    + getDeviceTemperatureLogs(deviceID : DeviceIDVO, sensorType : String, start : TimeStampVO, end : TimeStampVO) : Iterable<Log>}


interface LogFactory{
    + createLog(logID : LogIDVO, time : LocalDateTime, reading : SensorValueObject<?>, \nsensorID : SensorIDVO, deviceID : DeviceIDVO, sensorTypeID : SensorTypeIDVO) : Log
}

class LogFactoryImpl{
    + createLog(logID : LogIDVO, time : LocalDateTime, reading : SensorValueObject<?>, \nsensorID : SensorIDVO, deviceID : DeviceIDVO, sensorTypeID : SensorTypeIDVO) : Log
}

interface SensorValueFactory{
    + createSensorValue(reading : String, sensorTypeID : SensorTypeIDVO) : SensorValueObject<?>
}

class SensorValueFactoryImpl{
    - configuration : Configuration
    + SensorValueFactoryImpl(path : String)

}

class TemperatureValue{
    - value : double
    + TemperatureValue(reading : String)
    + getValue() : Double

    - isReadingValid() : boolean
}


interface LogService {
    + getMaxInstantaneousTempDifference(outdoorDeviceID : DeviceIDVO, \nindoorDeviceID : DeviceIDVO, initialTimeStamp : TimeStampVO, finalTimeStamp : TimeStampVO, deltaMin : DeltaVO) : String
}

class LogServiceImpl {
    - logRepository : LogRepository
    - deviceRepository : DeviceRepository
    - roomRepository : RoomRepository

    + LogServiceImpl(logRepository : LogRepository,\n deviceRepository : DeviceRepository, roomRepository : RoomRepository)

    + getMaxInstantaneousTempDifference(outdoorDeviceID : DeviceIDVO, \nindoorDeviceID : DeviceIDVO, initialTimeStamp : TimeStampVO, finalTimeStamp : TimeStampVO, deltaMin : DeltaVO) : String
    }

class GetMaxInstantaneousTemperatureDifferenceCTRL{
    - logService : LogService

    + GetMaxInstantaneousTemperatureDifferenceCTRL(logService : LogService)

    + getMaxInstantaneousTemperature(outdoorDeviceDTO : DeviceIDVO,\n indoorDeviceIDVO : DeviceDTO, timeConfigDTO : TimeConfigDTO) : String
}

class DeviceMapper{
    + createDeviceIDVO(deviceDTO : DeviceDTO) : DeviceIDVO
}

class DeviceDTO{
    - deviceID : String
    - deviceName : String
    - deviceModel : String
    - deviceStatus : String
    - roomID : String

    + getDeviceID() : String
}

class DeviceIDVO {
    - identifier : UUID

    + DeviceIDVO(identifier : UUID)
}

class SensorIDVO {
  - identifier : UUID

    + SensorIDVO(identifier : UUID)
    }

class SensorTypeIDVO {
  - identifier : UUID

    + SensorTypeIDVO(sensorType : String)
    }

class LogIDVO {
  - identifier : UUID

    + LogIDVO(identifier : UUID)
    }


class TimeConfigAssembler{
    - TimeConfigAssembler()

    + createDeltaVO((timeConfigDTO : TimeConfigDTO) : DeltaVO
    + createInitialTimeStamp(timeConfigDTO : TimeConfigDTO) : TimeStampVO
    + createFinalTimeStamp(timeConfigDTO : TimeConfigDTO) : TimeStampVO
}

class DeltaVO{
    - delta : int
    - DEFAULT : int

    + DeltaVO(delta : String)
    - definedDelta(delta : int) : String
}

class TimeStampVO{
    - timeStamp : LocalDateTime

    + TimeStampVO(localDateTime : LocalDateTime)
}


class TimeConfigDTO{
    - iDate : String
    - iTime : String
    - eDate : String
    -eTime : String
    -deltaMin : String

    + TimeConfigDTO(iDate : String, iTime : String, eDate : String, eTime : String)
}


class LogDataModel {
    - logID : String
    - time : LocalDateTime
    - reading : String
    - sensorID : String
    - deviceID : String
    - sensorTypeID : String

    + LogDataModel()

    + LogDataModel(log : Log)
}

class LogAssembler {
    + toDomain(logFactory : LogFactory, valueFactory : SensorValueFactory, logDataModel : LogDataModel)

    + toDomain(logFactory : LogFactory, valueFactory : SensorValueFactory, \nlogDataModelList : Iterable<LogDataModel>) : Iterable<Log>
}

class Log{
    - logID : LogIDVO
    - readingTime : LocalDateTime
    - reading : SensorValueObject<?>
    - sensorID : SensorIDVO
    - deviceID : DeviceIDVO
    - sensorTypeID : SensorTypeIDVO

    + Log(reading : SensorValueObject<?>, sensorID : SensorIDVO, \ndeviceID : DeviceIDVO, sensorTypeID : SensorTypeIDVO)

    + Log(logID : LogIDVO, readingTime : LocalDateTime, reading SensorValueObject<?>, sensorID : SensorIDVO, \ndeviceID : DeviceIDVO, sensorTypeID : SensorTypeIDVO)

}

interface SensorValueObject<T>

interface ValueObject<T>{
    + T getValue()
}


interface DomainID {
    + getID() : String
}


interface AggregateRoot {
    + getID() : DomainID
}

interface ILogRepositorySpringData{
    + findByDeviceIDAndTimeBetween(deviceID : String, from : LocalDateTime, to : LocalDateTime)

    + findByDeviceIDAndSensorTypeAndTimeBetween(deviceID : String, sensorType : String, start : LocalDateTime, end : LocalDateTime)
    }

@enduml