@startuml

skinparam ParticipantPadding 50

autonumber
title Use Case - Get Maximum Instantaneous Temperature Difference in a Given Period - Main Success Scenario

participant ":GetMaxInstantaneousTemperatureDifferenceCTRL" as C
participant ":DeviceMapper" as DM
participant ":TimeConfigAssembler" as TCA
participant ":TimeStampVO" as TS
participant ":DeltaVO" as DV
participant ":LogService" as LS
participant ":LogRepository" as LR


[o-> C : getMaxInstantaneousTemperature(outdoorDeviceDTO, indoorDeviceDTO, timeConfigDTO)
activate C

C -> DM : outdoorDeviceID = createDeviceIDVO(outdoorDeviceDTO)
activate DM
deactivate DM

C -> DM : indoorDeviceID = createDeviceIDVO(indoorDeviceDTO)
activate DM
deactivate DM

C -> TCA : initialTimeStamp = createInitialTimeStamp(timeConfigDTO)
activate TCA
create TS
TCA -> TS : create




C -> TCA : finalTimeStamp = createFinalTimeStamp(timeConfigDTO)
TCA -> TS : create

C -> TCA : delta = createDeltaVO(timeConfigDTO)

create DV
TCA -> DV : create
deactivate TCA

C -> LS : getMaxInstantaneousTempDifference(outdoorDeviceID, indoorDeviceID, initialTimeStamp, finalTimeStamp, delta)
activate LS

|||

activate LS
deactivate LS
|||
LS -> LR : outdoorDeviceLog = getDeviceTemperatureLogs(outdoorDeviceID,\nsensorTypeID, initialDateTime, finalDateTime)
activate LR
deactivate LR

LS -> LR : indoorDeviceLog = getDeviceTemperatureLogs(indoorDeviceID,\nsensorTypeID, initialDateTime, finalDateTime)
activate LR
deactivate LR
|||

LS -> LS : retrieveMaxTempDiffInAnInstant(outdoorDeviceLog, indoorDeviceLog, delta)
activate LS
deactivate LS
LS --> C : maxTemperatureAndInstant
deactivate LS

[o<-- C : maxTemperatureAndInstant
deactivate C

@enduml