@startuml

skinparam ParticipantPadding 50

autonumber
title Use Case - Get Maximum Instantaneous Temperature Difference in a Given Period v5.0 - Main Success Scenario

participant ":GetMaxInstantaneousTemperatureDifferenceCTRL" as C
participant ":DeviceMapper" as DM
participant ":TimeConfigAssembler" as TCA
participant ":LogService" as LS
participant ":TimeConfig" as TC
participant ":LogRepository" as LR


[o-> C : getMaxInstantaneousTemperature(outdoorDeviceDTO, indoorDeviceDTO, timeConfigDTO)
activate C

C -> DM : outdoorDeviceID = createDeviceIDVO(outdoorDeviceDTO)
activate DM
deactivate DM

C -> DM : indoorDeviceID = createDeviceIDVO(indoorDeviceDTO)
activate DM
deactivate DM

C -> TCA : timeConfig = createTimeConfig(timeConfigDTO)
activate TCA
deactivate TCA

C -> LS : getMaxInstantaneousTempDifference(outdoorDeviceID, indoorDeviceID, timeConfig)
activate LS
LS -> TC : initialDateTime = getInitialTimeStamp()
activate TC
LS -> TC : finalDateTime = getEndTimeStamp()
|||
deactivate TC

LS -> LS : delta = configureDelta(timeConfig)
activate LS
deactivate LS
|||
LS -> LR : outdoorDeviceLog = getDeviceTemperatureLogs(outdoorDeviceID,\nsensorTypeID, initialDateTime, finalDateTime)
activate LR
deactivate LR

LS -> LR : indoorDeviceLog = getDeviceTemperatureLogs(indoorDeviceID,\nsensorTypeID, initialDateTime, finalDateTime)
activate LR
deactivate LR
|||

LS -> LS : retrieveMaxTempDiffInAnInstant(outdoorDeviceLog, indoorDeviceLog, delta)
activate LS
deactivate LS
LS --> C : maxTemperature
deactivate LS

[o<-- C : maxTemperature
deactivate C

@enduml