@startuml
!theme cerulean
skinparam ParticipantPadding 50
autonumber
title User Story 5v2 - Main Success Scenario

participant ":addDeviceToRoomController" as C
participant ":CommonListOfRooms" as CU
participant ":Room" as R
participant ":ListOfDevices" as LD
participant ":ImplFactoryDevice" as FD
participant "dev : Device" as D

[o-> C : getListOfRooms()
activate C
C -> CU : getListOfRooms()
activate CU
CU -> CU : refreshMap()
activate CU
deactivate CU

CU -> CU : truncateList(roomDTOAndRoomMap)
activate CU
deactivate CU
CU --> C : roomDtoList
deactivate CU
[o<-- C : roomDtoList
deactivate C


[o-> C : addDeviceToRoom(deviceName,deviceModel,roomName)
activate C
C -> CU: getRoomByName(roomName)
activate CU
CU -> CU : refreshMap()
activate CU
deactivate CU
CU --> C : room
deactivate CU
C -> R : addDevice(deviceName,deviceModel,factoryDevice)
activate R
R -> R : deviceLocation = this.roomName
R -> LD : addDeviceToList(deviceName,deviceModel,deviceLocation,factoryDevice)
activate LD
LD -> FD : createDevice(deviceName,deviceModel,location)
activate FD
FD -> D **: <create>
FD --> LD : dev
deactivate FD
LD -> LD : add(dev)
LD --> R : return true
deactivate LD
R --> C : return true
deactivate R
[o<-- C : return true
deactivate C

@enduml