@startuml

title <size: 30> US05v2 Class Diagram

note "<b>Only methods related to\n<b>US05v2 are represented" as N1

skinparam linetype ortho

class AddDeviceToRoomCTRL{
    - houseRepo : HouseRepository
    - roomRepo : RoomRepository
    - deviceRepo : DeviceRepository
    - factoryDevice : FactoryDevice
    + getListOfRooms() : List<RoomDTO>
    + addDeviceToRoom(strDeviceName : String, strDeviceModel : String, roomDTO : RoomDTO) : boolean
}

class HouseRepository{
    - houseIDList : List<HouseID>

    + getHouseID()
}

class RoomRepository{
    - MAP : Map<RoomID, Room>

    + findAllByID(houseID : HouseID) : List<Room>
    + containsId(roomID : RoomID) : boolean
}


class RoomDTOMapper{
    + getRoomDTOList(roomList : List<Room>) : List<RoomDTO>
    + domainToDTO(room : Room) : RoomDTO
    + getRoomIDFromDTO(roomDTO : RoomDTO) : RoomID
}


class RoomDTO{
    - intRoomID : int
    - strRoomName : String
    - intHouseFloor : int
    - dbRoomWidth : double
    - dbRoomLength : double
    - dbRoomHeight : double

    + RoomDTO(strRoomName, intHouseFloor, dbRoomWidth, dbRoomLength, dbRoomHeight)
    + getID() : int
}



class Room <<Entity>> <<Root>>{
    - roomID : RoomID
    - roomName : RoomName
    - houseFloor : HouseFloor
    - roomDimensions : RoomDimensions
    - houseID : HouseID
}


interface FactoryDevice {
    + createDevice(strDeviceName : String, strDeviceModel : String, \nroomID : RoomID) : Device
}


class ImplFactoryDevice {
    + createDevice(strDeviceName : String, strDeviceModel : String, \nroomID : RoomID) : Device
}

class RoomID <<Value Object>><<ID>>{
    - intRoomID : int
    + RoomID(intRoomID : int)
}

class DeviceID <<Value Object>><<ID>>{
    - intDeviceID : int
    + DeviceID(intDeviceID : int)
}

class DeviceName <<Value Object>>{
    - strDeviceName : String
    + DeviceName(strDeviceName : String)
}

class DeviceModel <<Value Object>>{
    - strDeviceModel : String
    + DeviceModel(strDeviceModel : String)
}

class DeviceStatus <<Value Object>>{
    - bDeviceStatus : boolean
    + DeviceStatus(bDeviceStatus : boolean)
}


class Device <<Entity>> <<Root>>{
    - deviceID : DeviceID
    - deviceName : DeviceName
    - deviceModel : DeviceModel
    - status : Status
    - roomID : RoomID

    + Device(deviceName : DeviceName, deviceModel : DeviceModel, roomID : RoomID)
}

class DeviceRepository {
     - MAP : Map<DeviceID, Device>

     + save(device : Device) : boolean
}

interface Repository<T> {
    + findAll() : List<T>
    + findAllByID(domainID : DomainID) : List<T>
    + containsID(domainID : DomainID) : boolean
    + save(entity : T) : boolean
}


interface DomainID {

}


interface AggregateRoot {
}


AddDeviceToRoomCTRL ..> RoomDTOMapper
AddDeviceToRoomCTRL ..> HouseRepository
AddDeviceToRoomCTRL ..up> RoomRepository
AddDeviceToRoomCTRL ..up> DeviceRepository
RoomDTOMapper ..> RoomDTO
/'missing relationship between RoomMapper and RoomID?'/

AddDeviceToRoomCTRL ..> FactoryDevice
FactoryDevice <|.. ImplFactoryDevice
ImplFactoryDevice ..> DeviceName : <create>
ImplFactoryDevice ..> DeviceModel : <create>
ImplFactoryDevice ..> Device : <create>

Device "1" *-- "1" DeviceStatus
Device "1" o-- "1" RoomID
Device "1" o-- "1" DeviceName
Device "1" o-- "1" DeviceModel
Device "1" *-- "1" DeviceID

Repository <|.. RoomRepository
Room ..right|> AggregateRoot
Device ..up|> AggregateRoot
Repository <|.. DeviceRepository
DeviceRepository "1" o-- "*" Device
RoomRepository "1" o-- "*" Room

DomainID <|..up RoomID
DomainID <|..up DeviceID


@enduml