@startuml

skinparam ParticipantPadding 50

autonumber
title User Story 5v2 - Main Success Scenario

participant ":AddDeviceToRoomCTRL" as C
participant ":RoomDTOMapper" as RM
participant ":RoomDTO" as RDTO
participant "roomID : RoomID" as RID
participant ":RoomService" as RS
participant ":RoomRepository" as RR
participant ":DeviceDTOMapper" as DDM
participant "deviceName : DeviceName" as DN
participant "deviceModel : DeviceModel" as DM
participant ":DeviceService" as DS
participant ":ImplFactoryDevice" as FD
participant "device : Device" as D
participant "deviceID : DeviceID" as DID
participant "deviceStatus : DeviceStatus" as DStat
participant ":DeviceRepository" as DR

/'note over RM : Should include interaction with RoomDTO?
note over FD : Should receive VOs or create them?
note over C : logic to save the device?? if true/false??'/

skinparam messageAlign center
ref over C, RM, RR : US03 Controller - Get list of rooms


[o-> C : addDeviceToRoom(deviceDTO, RoomDTO)
activate C
C -> RM : getDtoID(RoomDTO)
activate RM
RM -> RDTO : getID()
activate RDTO
RDTO -> RID ** : create(strRoomID)
RDTO --> RM : roomID
deactivate RDTO
RM --> C : roomID
deactivate RM

C -> RS : roomExists(roomID)
activate RS
RS -> RR : containsID(roomID)
activate RR
RR --> RS : <font color=green>**true**</font>
deactivate RR
RS --> C : <font color=green>**true**</font>
deactivate RS

C -> DDM : getDeviceName(deviceDTO)
activate DDM
DDM -> DN ** : create(strDeviceName)
DDM --> C : deviceName
deactivate DDM
C -> DDM : getDeviceModel(deviceDTO)
activate DDM
DDM -> DM ** : create(strDeviceModel)
DDM --> C : deviceModel
deactivate DDM

C -> DS : createDevice(deviceName, deviceModel, roomID)
activate DS
DS -> FD : createDevice(deviceName, deviceModel, roomID)
activate FD
FD -> D ** : create(deviceName, deviceModel, roomID)
activate D
D -> DID ** : create(uuid)
D -> DStat ** : create(true)
deactivate D
FD --> DS : device
deactivate FD
DS --> C : device
deactivate DS

C -> DS : saveDevice(device)
activate DS
DS -> DR : save(device)
activate DR
DR -> DR : put(deviceID, device)
activate DR
deactivate DR
DR --> DS : <font color=green>**true**</font>
deactivate DR

DS --> C : <font color=green>**true**</font>
deactivate DS

[o<-- C : <font color=green>**true**</font>
deactivate C

@enduml