 @startuml
title User Story 8 - Main Success Scenario
!theme cerulean
autonumber

participant ":deactivateDeviceCTRL" as C
participant ":CommonListOfRooms" as CU
participant ":House" as H
participant ":ListOfRooms" as LR
participant ":RoomDTOMapper" as RM
participant ":CommonListOfDevices" as CD
participant ":Room" as R
participant ":ListOfDevices" as LD
participant ":DeviceDTOMapper" as DM
participant "device:Device" as D



[o-> C : getRooms()
activate C
C -> CU : getRooms()
activate CU
CU -> H : getListOfRooms()
activate H
H -> LR : getListOfRooms()
activate LR
LR -> LR : listOfRooms = cloneList()
activate LR
deactivate LR
LR --> H : listOfRooms
deactivate LR
H --> CU : listOfRooms
deactivate H
CU -> RM : domainToRoomDTOList(listOfRooms)
activate RM
loop for each room in room list
RM -> RM : RoomDTO = domainToDTO(room)
activate RM
deactivate RM
RM -> RM : put(RoomDTO)
activate RM
deactivate RM
end loop
RM --> CU : roomAndRoomDtoList
deactivate RM
CU -> CU : roomDtoList = truncateList(roomAndRoomDtoList)
activate CU
deactivate CU
CU --> C : roomDtoList
deactivate CU
[o<-- C : roomDtoList
deactivate C

[o-> C : getListOfDevices(roomDTO)
activate C
C -> CU: getRoom(roomDTO)
activate CU
CU --> C : room
deactivate CU
C -> CD : getDevices()
activate CD
CD -> R : getListOfDevices()
activate R
R -> LD : getDevices()
activate LD
LD -> LD : listOfDevices = cloneList()
activate LD
deactivate LD
LD --> R : listOfDevices
deactivate LD
R --> CD : listOfDevices
deactivate R
CD -> DM : domainToDeviceDTOList(deviceList)
activate DM
loop for each device in device list
DM -> DM : DeviceDTO = domainToDTO(device)
activate DM
deactivate DM
DM -> DM : put(DeviceDTO)
activate DM
deactivate DM
end loop
DM --> CD : deviceAndDeviceDtoList
deactivate DM
CD -> CD : dtoDeviceList = truncateList(deviceAndDeviceDtoList)
activate CD
deactivate CD
CD --> C : dtoDeviceList
deactivate CD
[o<-- C : dtoDeviceList
deactivate C

[o-> C : deactivateDevice(deviceDTO)
activate C
C -> CU : device = getDevice(deviceDTO)
C -> D : deactivateDevice()
activate D
D -> C : false
deactivate D
[o<-- C : false
deactivate C
@enduml