 @startuml
title User Story 8 - Main Success Scenario
!theme cerulean
autonumber

participant ":deactivateDeviceCTRL" as C
participant ":CommonListOfRooms" as CU
participant ":CommonListOfDevices" as CD
participant "device:Device" as D



[o-> C : getListOfRooms()
activate C
C -> CU : getListOfRooms()
activate CU
CU -> CU : refreshMap()
activate CU
deactivate CU

CU -> CU : truncateList(roomDTOAndRoomMap)
activate CU
deactivate CU
CU --> C : roomDtoList
deactivate CU
[o<-- C : roomDtoList
deactivate C

[o-> C : getListOfDevices(roomName)
activate C
C -> CU: getRoomByName(roomName)
activate CU
CU -> CU : refreshMap()
activate CU
deactivate CU
CU --> C : room
deactivate CU
C -> CD : getListOfDevices(room)
activate CD
CD -> CD : refreshMap(room)
activate CD
deactivate CD

CD -> CD : truncateList(deviceDTOAndDeviceMap)
activate CD
deactivate CD
CD --> C : dtoDeviceList
deactivate CD
[o<-- C : dtoDeviceList
deactivate C

[o-> C : deactivateDevice(deviceName)
activate C
C -> CD : getDeviceByName(deviceName, room)
activate CD
CD -> CD : refreshMap(room)
activate CD
deactivate CD
CD --> C :
deactivate CD
C -> D : deactivateDevice()
activate D
D --> C : false
deactivate D
[o<-- C : false
deactivate C
@enduml