@startuml

skinparam ParticipantPadding 50
autonumber
title Use Case Get List Of Devices v5.0 - Main Success Scenario

participant ":GetListOfDevicesCTRL" as C
participant ":RoomMapper" as RM
participant ":RoomDTO" as RDTO
participant ":RoomIDVO" as RID
participant ":DeviceServiceImpl" as DS
participant ":DeviceRepository" as DR
participant ":DeviceMapper" as DM



[o-> C : getListOfDevices(roomDTO)
activate C

C -> RM : createRoomIDVO(RoomDTO)
activate RM

RM -> RDTO : getId()
activate RDTO

RDTO --> RM : roomID
deactivate RDTO

RM -> RID ** : create(roomID)

RM --> C : roomIDVO
deactivate RM

C -> DS : getListOfDevicesInARoom(roomIDVO)
activate DS



DS -> DR : findByRoomId(roomIDVO)
activate DR

DR --> DS : deviceList
deactivate DR


DS -> DM : domainToDTO(deviceList)

activate DM
loop for each device in device list
DM -> DM : domainToDTO(deviceList)
activate DM
deactivate DM

end loop
DM --> DS : deviceDTOList
deactivate DM

DS --> C : deviceDTOList
deactivate DS

[o<-- C : deviceDTOList
deactivate C


@enduml
