@startuml

skinparam ParticipantPadding 50
autonumber
title User Story 6 - Main Success Scenario

participant ":GetListOfDevicesCTRL" as C
participant ":RoomMapper" as RM
participant ":RoomDTO" as RDTO
participant ":RoomIDVO" as RID
participant ":RoomService" as RS
participant ":DeviceService" as DS
participant ":DeviceRepository" as DR
participant ":DeviceMapper" as DM



[o-> C : getListOfDevices(roomDTO)
activate C

C -> RM : createRoomIDVO(RoomDTO)
activate RM

RM -> RDTO : getId()
activate RDTO

RDTO --> RM : id
deactivate RDTO

RM -> RID ** : create(id)

RM --> C : roomIDVO
deactivate RM

C -> RS : isPresent(roomIDVO)
activate RS

RS --> C : false
deactivate RS

C -> DS : getListOfDevicesInARoom(roomIDVO)
activate DS

DS -> DR : findByRoomId(roomIDVO)
activate DR

DR -> DR : clone(listOfDevices)
activate DR
deactivate DR

DR --> DS : clonedListOfDevices

deactivate DR



DS --> C : clonedListOfDevices

deactivate DS

C -> DM : domainToDTO(clonedListOfDevices)

activate DM
loop for each device in cloned device list
DM -> DM : domainToDTO(clonedListOfDevices)
activate DM
deactivate DM

end loop
DM --> C : deviceDTOList
deactivate DM


[o<-- C : deviceDTOList

deactivate C


@enduml
