@startuml
title <size: 30> Switch Sensor Class Diagram

interface Sensor {
    + getSensorTypeID() : SensorTypeIDVO;
    + getDeviceID() : DeviceIDVO;
    + getSensorName() : SensorNameVO;
}


interface ValueObject<T> {
    + getValue() : T
}

class SensorNameVO{
    - sensorName : String
    + getValue() : String
}

class DeviceIDVO{
    - deviceID : UUID
    + getID() : String
}

class SensorTypeIDVO{
    - sensorTypeID : String
    + getID() : String
}

class SensorIDVO{
    - identifier : UUID
    + getValue() : String
}


class SwitchSensor{
    - sensorName : SensorNameVO
    - deviceID : DeviceIDVO
    - sensorType : SensorTypeIDVO
    - sensorID : SensorIDVO

    + getReading(simHardware : SimHardware) : ValueObject<Integer>
}

class SwitchValue{
    - switchValue : String

    + getValue() : String
    - isReadingValid(switchValue : String) : boolean
}

class SimHardware{
    + getValue() : String
}

interface SensorExternalService {
+getValue() : String
}

ValueObject <|.. SwitchValue
Sensor <|.. SwitchSensor
SwitchSensor .right.> SwitchValue
SwitchSensor .left.> SimHardware
SwitchSensor .down.> SensorNameVO
SwitchSensor .down.> DeviceIDVO
SwitchSensor .down.> SensorTypeIDVO
SwitchSensor .down.> SensorIDVO
SimHardware ..|> SensorExternalService

@enduml