@startuml
!theme cerulean
title User Story 9 - Main Success Scenario

autonumber

participant ":GetDevicesByFunctionalityCTRL" as C
participant ":House" as H
participant ":ListOfRooms" as LOR
participant ":Room" as R
participant ":ListOfDevices" as LOD
participant ":Device" as D
participant ":DeviceDTOMapper" as DM
skinparam ParticipantPadding 50

[o-> C : getDevicesByFunctionality()
activate C
C -> H : getDevicesByFunctionality()
activate H
H -> H : updateHouseFunctionalities()
activate H
H -> LOR : roomList = getRoomList
loop for every room in roomList
   H -> R : getRoomFunctionalities()
   activate R
   R -> R : updateRoomFunctionalities()
   activate R
   R -> LOD : deviceList = getDeviceList
loop for every device in room
   R -> D : devFunctionalities = getDeviceFunctionalities()
end
deactivate R
R --> H : roomFunctionalities
deactivate R
end
deactivate H
H --> C : functionalitiesMap
deactivate H
C -> DM : domainMapToDTO(functionalitiesMap)
activate DM
loop for every deviceList in functionalitiesMap
DM -> DM : domainToDTO(deviceList)
activate DM
loop for every device in deviceList
DM -> DM : deviceDTO = domainToDTO(device)
end
deactivate DM
DM --> C : dtoFunctionalitiesMap
deactivate DM
[o<-- C : dtoFunctionalitiesMap
deactivate C
@enduml