@startuml
title <size: 30> US09 Class Diagram
note "<b>Only methods related to\n<b>US09 are represented" as N1
skinparam linetype ortho

class GetDevicesByFunctionalityCTRL {
    - deviceRepo : DeviceRepository
    - sensorRepo : SensorRepository
    + getListOfDevicesByFunctionality() : Map<FunctionalityDTO, DeviceDTO>
}

class GetDevicesByFunctionalitySERVICE {
    - functionalityDeviceIdMap : Map<Functionality, DeviceId>
    - functionalityList : List<Functionality>
    - functionalityDTOList : List<FunctionalityDTO>
    - deviceIdList : List<DeviceId>
    - deviceList : List<Device>
    - deviceDTOList : List<DeviceDTO>
    + getListOfDevicesByFunctionality() : Map<FunctionalityDTO, DeviceDTO>
    + extractFunctionality( Map<Functionality, DeviceId> ) : List<Functionality>
    + extractDeviceId ( Map<Functionality, DeviceId> ) : List<DeviceId>
    + deviceIdToDevice ( List<DeviceID ) : List<Device>
    + createFunctionalityDTODeviceDTOList ( List<FunctionalityDTO>, List<DeviceDTO>, Map<Functionality, DeviceId>) : Map<FunctionalityDTO, DeviceDTO>
}

class Device <<Entity>> <<Root>>{
    -deviceID : DeviceID
    -deviceModel : DeviceModel
    -status : Status
    -roomId : RoomId
    +getDeviceID() : DeviceID
    +getDeviceModel() : DeviceModel
    +getStatus() : Status
    +getRoomID() : RoomID
}

class DeviceID <<Identity>> <<VO>> {
    -deviceID : String
    +getDeviceID() : String
}

class DeviceModel <<VO>> {
    -deviceModel : String
    +getDeviceModel() : String
}

class RoomID <<VO>> {
    -roomID : String
    +getRoomID() : String
}

class Status <<VO>> {
    -status : boolean
    +getStatus : boolean
}

class DeviceRepository {
    - map : Map<DeviceID, Device>
    + getListOfAllDevices() : Map<DeviceID, Device>
}

class SensorRepository {
    +getFunctionalityDeviceIdMap() : Map<Functionality, DeviceId>
}

class Sensor <<Entity>> <<Root>>{
    - sensorID : SensorID
    - sensorType : SensorType
    - deviceID : DeviceID
    +getType() : String
    +getDeviceID() : String
    +getSensorID() : String
}

class SensorID <<VO>> {
    -sensorID : String
    +getSensorID() : String
}

class SensorType <<VO>> {
    -sensorType : String
    +getSensorType() : String
}

class SensorDTOMapper {
    +domainToDTO ( List<Functionality> ) : List<FunctionalityDTO>
}

class DeviceDTOMapper {
    +domainToDTO ( List<Device> ) : List<DeviceDTO>
}

GetDevicesByFunctionalityCTRL ..> GetDevicesByFunctionalitySERVICE

GetDevicesByFunctionalitySERVICE ..> DeviceRepository
GetDevicesByFunctionalitySERVICE ..> SensorDTOMapper
GetDevicesByFunctionalitySERVICE ..> SensorRepository
GetDevicesByFunctionalitySERVICE ..> DeviceDTOMapper

DeviceRepository o-- Device
DeviceDTOMapper --> Device

SensorRepository o-- Sensor
SensorDTOMapper --> Sensor

Device *..left DeviceModel
Device *..right DeviceID
Device *.. RoomID
Device *.. Status

Sensor *..right SensorType
Sensor *..left DeviceID
Sensor *.. SensorID

@enduml

