@startuml

title User Story 9 - Main Success Scenario v4.2

autonumber

participant ":GetDevicesByFunctionalityCTRL" as C
participant ":SensorService" as SS
participant ":SensorRepo" as SR
participant ":DeviceService" as DS
participant ":DeviceRepo" as DR
participant ":DeviceDTOMapper" as DM

'1
    [o-> C : getListOfDevicesByFuncionality()
    activate C

    C -> SS : getListOfDevicesByFuncionality()
    activate SS

    SS -> SR : findall() : List<Sensor>

note right of SS: Method abstracted, to have own sequence diagram
    SS -> SS : getUniqueSensorTypeIDasStrbyDeviceIDVO() : sensorTypeToDeviceIDMap

    SS --> C : sensorTypeIDstrToDeviceIDVOMap
    deactivate SS

    C -> DS : getSensorTypeIDstrToDeviceMap (sensorTypeIDstrToDeviceIDVOMap)
    activate DS
loop for all DeviceIDVO
    DS -> DR : findByID(DeviceIDVO) : Device
end loop

    DS --> C : sensorTypeIDstrToDeviceMap
    deactivate DS
note right of DM: DTO conversion abstracted
    C -> DM : domainToDTO (sensorTypeIDstrToDeviceMap) : sensorTypeIDstrToDeviceDTOMap
    [o<-- C : sensorTypeIDstrToDeviceDTOMap
    deactivate C



@enduml