@startuml

title User Story 9 - Main Success Scenario v4.3

autonumber

participant ":GetDevicesByFunctionalityCTRL" as C
participant ":SensorService" as SS
participant ":SensorRepo" as SR
participant "sensor:Sensor" as S

participant ":ActuatorService" as AS
participant ":ActuatorRepo" as AR
participant "actuator : Actuator" as A

participant ":DeviceService" as DS
participant ":DeviceRepo" as DR
participant ":DeviceDTOMapper" as DM

'1
    [o-> C : getListOfDevicesByFuncionality()
    activate C

    C -> SS : getListOfDeviceIDsByFunctionality()
    activate SS
    SS -> SR : findall() : List<Sensor>
loop for all Sensors
    SS -> S : str_ID : getSensorTypeID().getID()
    activate S
    SS -> S : DeviceIDVO : getDeviceID()
    deactivate S
end loop
    SS --> C : sensorTypeIDstrToDeviceIDVoMap
    deactivate SS
    
    C -> AS : getListOfDeviceIDsByFunctionality()
    activate AS
    AS -> AR : findall() : List<Actuator>
loop for all Actuators
    AS -> A : str_ID : getSensorTypeID().getID()
    activate A
    AS -> A : DeviceIDVO : getDeviceID()
    deactivate A
end loop    
    AS --> C : sensorTypeIDstrToDeviceIDVoMap
    deactivate AS

    C -> DS : getDevices(sensorTypeIDstrToDeviceIDVoMap)
    activate DS
    loop for all DeviceIDVO
    DS -> DR : Device : findById(DeviceIDVO)
end loop
    DS --> C : sensorTypeIDstrToDeviceMap
    deactivate DS

note right of C: domainToDTO method abstracted for visibility.
    C -> DM : sensorTypeIDstrToDeviceDTOMap = domainToDTO(sensorTypeIDstrToDeviceMap)
    
    [o<-- C : sensorTypeIDstrToDeviceDTOMap
    deactivate C



@enduml