@startuml
skinparam ParticipantPadding 50
    title <size:30> Use Case - Add Sensor to Device v5.0 - Main Success Scenario
    autonumber

participant ":AddSensorToDeviceCTRL" as C

participant ":SensorMapper" as SM
participant ":SensorTypeMapper" as STM
participant ":DeviceMapper" as DM
participant ":SensorServiceImpl" as SS
participant ":SensorTypeRepositoryMem" as STR
participant ":DeviceRepositoryMem" as DR
participant ":Device" as D
participant ":SensorFactoryImpl" as SF
participant ":SensorRepositoryMem" as SR
participant "sensor : Sensor" as S





[o-> C : addSensorToDevice(deviceDTO, sensorDTO, sensorTypeDTO)
activate C
C -> SM : createSensorNameVO(sensorDTO)
activate SM
SM --> C : sensorNameVO
deactivate SM
C -> STM : createSensorTypeIDVO(sensorTypeDTO)
activate STM
STM --> C : sensorTypeIDVO
deactivate STM
C -> DM : createDeviceIDVO(deviceDTO)
activate DM
DM --> C : deviceIDVO
deactivate DM
C -> SS : addSensor(sensorNameVO, deviceIDVO, sensorTypeIDVO)
activate SS
SS -> STR : isPresent(sensorTypeIDVO)
activate STR
STR --> SS : true
deactivate STR
SS -> DR : findById(deviceIDVO)
activate DR
DR --> SS : device
deactivate DR
SS -> D : isActive(device)
activate D
D --> SS : true
deactivate D
SS -> SF : createSensor(sensorNameVO, deviceIDVO, sensorTypeIDVO)
activate SF
SF -> S** : create(sensorNameVO, deviceIDVO, sensorTypeIDVO)
SF --> SS : sensor
deactivate SF
SS -> SR : save(sensor)
activate SR
SR --> SS : true
deactivate SR
SS --> C : true
deactivate SS
[o<-- C : true
deactivate C

@enduml