@startuml
skinparam ParticipantPadding 50
    title User Story 7: Main Success Scenario
    autonumber

participant ":AddSensorToDeviceCTRL" as C
participant ":SensorTypeService" as STS
participant ":SensorTypeRepository" as STR
participant ":SensorMapper" as SM
participant ":SensorTypeMapper" as STM
participant ":DeviceMapper" as DM
participant ":DeviceService" as DS
participant ":DeviceRepository" as DR
participant ":SensorService" as SS
participant ":SensorFactory" as SF
participant "sensor : Sensor" as S
participant ":SensorRepository" as SR

[o-> C : addSensorToDevice(deviceDTO, sensorDTO, sensorTypeDTO)
activate C
C -> SM : createSensorNameVO(sensorDTO)
activate SM
SM --> C : sensorNameVO
deactivate SM
C -> STM : createSensorTypeIDVO(sensorTypeDTO)
activate STM
STM --> C : sensorTypeIDVO
deactivate STM
C -> DM : createDeviceIDVO(deviceDTO)
activate DM
DM --> C : deviceIDVO
deactivate DM
C -> STS : sensorTypeExists(sensorTypeIDVO)
activate STS
STS -> STR : isPresent(sensorTypeIDVO)
activate STR
STR --> STS : true
deactivate STR
STS --> C : true
deactivate STS
C -> DS : isActive(deviceIDVO)
activate DS
DS -> DR : findByID(deviceIDVO)
activate DR
DR --> DS : device
deactivate DR
DS -> DS : isActive(device)
activate DS
deactivate DS
DS --> C : true
deactivate DS
deactivate STS
deactivate STM
C -> SS : addSensor(sensorNameVO, deviceIDVO, sensorTypeIDVO)
activate SS
SS -> SF : createSensor(sensorNameVO, deviceIDVO, sensorTypeIDVO)
activate SF
SF -> S** : create(sensorNameVO, deviceIDVO, sensorTypeIDVO)
SF --> SS : sensor
deactivate SF
SS -> SR : save(sensor)
activate SR
SR --> SS : true
deactivate SR
SS --> C : true
deactivate SS
[o<-- C : true
deactivate C
@enduml