@startuml

title <size: 30> US07 Class Diagram
note "<b>Only methods related to\n<b>US07 are represented" as N1
skinparam linetype ortho

       AddSensorToDeviceCTRL  ..> SensorRepository
       AddSensorToDeviceCTRL  ..> DeviceRepository
       AddSensorToDeviceCTRL  ..> RoomRepository
       AddSensorToDeviceCTRL  ..> SensorFactory
       SensorFactory -- Sensor : creates >
       AddSensorToDeviceCTRL ..> RoomDTOMapper
       AddSensorToDeviceCTRL ..> DeviceDTOMapper
       DeviceDTOMapper ..> DeviceDTO
       RoomDTOMapper ..> RoomDTO


    class AddSensorToDeviceCTRL{
        -houseRepository: HouseRepository
        -roomRepository: RoomRepository
        -deviceRepository: DeviceRepository
        -sensorRepository: SensorRepository
        -sensorFactory: SensorFactory
        +getListOfRooms(): List<RoomDTO>
        +getListOfDevices(roomId : RoomId): List<DeviceDTO>
        +createSensor(deviceId: DeviceId, sensorName: String, typeOfSensor: String): Sensor
        +save(sensor) : boolean
    }

    class RoomDTO{
        -roomName: String
        -houseFloor: int
        -roomWidth: double
        -roomLength: double
        -roomHeight: double
    }

    class DeviceDTO{
        -deviceName: String
        -deviceModel: String
        -location: String
        -status: boolean
    }

    class RoomDTOMapper{
        +getRoomDTOList(listOfRooms : List<Room>) : LinkedHashMap<RoomDTO, Room>
        +domainToDTO(room: Room) : RoomDTO
        +getRoomId(roomDTO) : RoomId
    }

    class DeviceDTOMapper{
        +domainToDTO(device: Device) : DeviceDTO
        +getDeviceDTOList(listOfDevices : List<Device>) : LinkedHashMap<DeviceDTO, Device>
        +getDeviceId(deviceDTO) : DeviceId
    }


   class RoomRepository{
        -roomMap : Map<RoomId, Room>
        +getRoomList() : List<Room>
        -cloneListOfRooms(List<Room>) : List<Room>
   }

    class DeviceRepository{
        -deviceMap : Map<DeviceId, Device>
        +getDeviceList(roomId : RoomId) : List<Device>
        -cloneListOfDevices(List<Device>) : List<Device>
    }

    class SensorRepository{
        -sensorMap : Map<SensorId, Sensor>
        +getSensorList(deviceId : DeviceId) : List<Sensor>
        -cloneListOfSensors(List<Sensor>) : List<Sensor>
    }


    interface Sensor{
        +getName(): String
        +getType(): String
        +getValue(): double
    }


@enduml