@startuml

title <size: 30> Use Case: Add Actuator to Device Class Diagram v5.3
note "<b>Only methods related to\n<b>Add Actuator to Device are represented" as N1
skinparam linetype ortho

       AddActuatorToDeviceCTRL ..> ActuatorMapper
       AddActuatorToDeviceCTRL ..> ActuatorTypeMapper
       AddActuatorToDeviceCTRL ..> DeviceMapper
       AddActuatorToDeviceCTRL ..> ActuatorService
       ActuatorServiceImpl ..> ActuatorFactory
       ActuatorServiceImpl .up.> ActuatorTypeRepository
       ActuatorServiceImpl .up.> ActuatorRepository
       ActuatorServiceImpl .up.> DeviceRepository
       ActuatorServiceImpl ..> Device
       ActuatorFactoryImpl -down- SwitchActuator : creates >
       ActuatorFactoryImpl -down- RollerBlindActuator : creates >
       ActuatorFactoryImpl -down- IntegerActuator : creates >
       ActuatorFactoryImpl -down- DecimalActuator : creates >
       AggregateRoot <|-up- Actuator
       Actuator <|.up. SwitchActuator
       Actuator <|.up. RollerBlindActuator
       Actuator <|.up. IntegerActuator
       Actuator <|.up. DecimalActuator
       Device ..|> AggregateRoot
       DeviceMapper ..> DeviceDTO
       DeviceMapper -- DeviceIDVO : creates >
       ActuatorMapper .right.> ActuatorDTO
       ActuatorMapper -- ActuatorNameVO : creates >
       ActuatorTypeMapper ..> ActuatorTypeDTO
       ActuatorTypeMapper -- ActuatorTypeIDVO : creates >
       DeviceRepository -up-|> Repository
       ActuatorRepository -up-|> Repository
       ActuatorTypeRepository -up-|> Repository
       ActuatorMapper -- IntegerSettingsVO : creates >
       ActuatorMapper -- DecimalSettingsVO : creates >
       IntegerSettingsVO ..|> Settings
       DecimalSettingsVO ..|> Settings
       ActuatorNameVO ..|> ValueObject
       ActuatorTypeIDVO ..|> ValueObject
       DeviceIDVO ..|> ValueObject
       ActuatorServiceImpl ..|> ActuatorService
       ActuatorRepositoryMem ..|> ActuatorRepository
       ActuatorRepositoryJPA ..|> ActuatorRepository
       ActuatorFactoryImpl .up.|> ActuatorFactory
       ActuatorRepositoryJPA .up.> ActuatorAssembler
       ActuatorAssembler -up- "*"ActuatorDataModel : create >



    class AddActuatorToDeviceCTRL{
        -actuatorService: ActuatorService
        +AddActuatorToDeviceCTRL(actuatorService)
        +addActuatorToDevice(sensorDTO, sensorTypeDTO, deviceDTO): boolean
    }

    class ActuatorServiceImpl{
        -actuatorRepository: ActuatorRepository
        -actuatorFactory: ActuatorFactory
        -actuatorTypeRepository: ActuatorTypeRepository
        -deviceRepository: DeviceRepository
        +ActuatorService(actuatorFactory, actuatorRepository, actuatorTypeRepository, deviceRepository)
        +addActuator(actuatorNameVO, deviceIDVO, actuatorTypeIDVO): boolean
    }

    class ActuatorRepositoryMem{
        -actuatorMap : Map<ActuatorIDVO, Actuator>
        +save(actuator : Actuator): boolean
    }

    class ActuatorRepositoryJPA{
            -actuatorFactory : ActuatorFactory
            +save(actuator : Actuator): boolean
    }




    class ActuatorFactoryImpl{
        -filePath: String
        -configuration: Configuration
    }

    class ActuatorMapper{
        +ActuatorMapper()
        +createActuatorNameVO(sensorDTO): ActuatorNameVO
    }

    class ActuatorTypeMapper{
        +ActuatorTypeMapper()
        +domainToDTO(actuatorTypeList): List<ActuatorTypeDTO>
        +createActuatorTypeIDVO(actuatorTypeDTO): ActuatorTypeIDVO
    }

    class DeviceMapper{
        +createDeviceIDVO(deviceDTO): DeviceIDVO
    }

    class Device {
        -deviceName: DeviceNameVO
        -deviceModel: DeviceModelVO
        -roomID: RoomIDVO
        -deviceStatus: DeviceStatusVO
        -deviceID: DeviceIDVO
        +Device(deviceID, deviceName, deviceModel, roomID, deviceStatus)
        +isActive(device): boolean
    }

    class ActuatorDTO{
        -actuatorName: String
        -actuatorID: String
        -deviceID: String
        -actuatorType: String
        +getActuatorName(): String
    }

    class ActuatorTypeDTO{
        -actuatorTypeID: String
        +getActuatorTypeID(): String
    }

    class DeviceDTO{
        -deviceID: String
        -deviceName: String
        -deviceModel: String
        -roomID: String
        -deviceStatus: boolean
        +getDeviceID(): String
    }

    interface Repository{
        + findAll() : List<T>
        + findByID(id : ID) : T
        + isPresent(id : ID) : boolean
        + save(ent : T) : boolean
    }

    class ActuatorNameVO{
            -actuatorName: String
            +ActuatorNameVO(actuatorName)
        }

        class ActuatorTypeIDVO{
            -actuatorTypeID: String
            +ActuatorTypeIDVO(actuatorTypeID)
        }

        class DeviceIDVO{
            -deviceID: UUID
            +DeviceIDVO(deviceID : UUID)
        }

        class IntegerSettingsVO{
        -lowerLimit: int
        -upperLimit : int
        -validLimits(lowerLimit, upperLimit): boolean
        +getValue(): int[]
        }

        class DecimalSettingsVO{
        -lowerLimit: double
        -upperLimit : double
        -precision : double
        -validSettings(lowerLimit, upperLimit, precision): boolean
        -countDecimalPlaces(value : double): int
        +getValue(): double[]
        }


    interface Actuator{
    +getActuatorTypeID() : ActuatorTypeIDVO
    +getDeviceID() : DeviceIDVO
    +getActuatorName() : ActuatorNameVO
    +getLowerLimit() : String
    +getUpperLimit() : String
    +getPrecision() : String
    }

    interface AggregateRoot{
    +getID() : DomainID
    }

    class SwitchActuator{
    +getID() : ActuatorIDVO
    }

    class RollerBlindActuator{
    +getID() : ActuatorIDVO
    }

    class IntegerActuator {
    +getID() : ActuatorIDVO
    }

    class DecimalActuator{
    +getID() : ActuatorIDVO
    }

    interface Settings{

    }

    interface ValueObject{
    +getValue(): T
    }
    interface ActuatorTypeRepository{

                }

    interface ActuatorService{
        +addActuator(actuatorNameVO, deviceIDVO, actuatorTypeIDVO): boolean
    }

    interface ActuatorRepository{

    }

    interface DeviceRepository{

    }

   interface ActuatorFactory {
    +createActuator(actuatorNameVO, actuatorTypeIDVO, deviceIDVO, settingsVO) : Actuator
    +createActuator(actuatorIDVO, actuatorNameVO, actuatorTypeIDVO, deviceIDVO, settingsVO) : Actuator
    }

    class ActuatorAssembler{
    +toDomain(actuatorFactory, actuatorDataModel) : Actuator
    +toDomainList(actuatorFactory, actuatorDataModels) : List<Actuator>
    }

    class ActuatorDataModel{
    -actuatorID: String
    -actuatorName: String
    -actuatorTypeID: String
    -deviceID: String
    -lowerLimit: String
    -upperLimit: String
    -precision: String
    }


@enduml