@startuml
skinparam ParticipantPadding 50
    title Add Actuator to Device: Main Success Scenario
    autonumber

participant ":AddActuatorToDeviceCTRL" as C
participant ":ActuatorMapper" as AM
participant ":ActuatorTypeMapper" as ATM
participant ":DeviceMapper" as DM
participant ":ActuatorService" as AS
participant ":ActuatorTypeRepository" as ATR
participant ":DeviceRepository" as DR
participant ":Device" as D
participant ":ActuatorFactory" as AF
participant "actuator : Actuator" as A
participant ":ActuatorRepository" as AR





[o-> C : boolean : addActuatorToDevice(actuatorDTO, actuatorTypeDTO, deviceDTO)
C -> AM : actuatorNameVO : createActuatorNameVO(actuatorDTO)
activate AM
deactivate AM
C -> ATM : actuatorTypeIDVO : createActuatorTypeIDVO(actuatorTypeDTO)
activate ATM
deactivate ATM
C -> DM : deviceIDVO : createDeviceID(deviceDTO)
activate DM
deactivate DM
C -> AM : settings : createSettingsVO(actuatorDTO)
activate AM
deactivate AM
C -> AS : boolean : addActuatorToDevice(actuatorNameVO, actuatorTypeIDVO, deviceNameVO, settings)
activate AS
AS -> ATR : boolean : isPresent(actuatorTypeIDVO)
activate ATR
deactivate ATR
AS -> DR : device : findByID(deviceIDVO)
activate DR
deactivate DR
AS -> D : boolean : isActive(device)
activate D
deactivate D
AS ->AF : actuator : create(actuatorNameVO,  actuatorTypeIDVO, deviceIDVO, settings)
activate AF
AF -> A** : actuator : create(actuatorNameVO,  actuatorTypeIDVO, deviceIDVO, settings)
deactivate AF
AS -> AR : boolean : save(actuator)
deactivate AS
activate AR
deactivate AR
deactivate C
@enduml