@startuml
title <size: 30> Domain Model

skinparam style strictuml
hide empty members
left to right direction
skinparam ClassFontSize 18

class House {
houseName
}

class Address {
doorReference
buildingNumber
streetName
city
country
zipCode
}

class GPS {
latitude
longitude
}

class Room {
name
houseFloor
}

class RoomDimensions {
width
length
height
}

class Device {
deviceName
deviceModel
roomName
}


class Sensor {
}

class SensorType {
}

class Actuator {
}

class ActuatorType {
}

class User {
}

class UserRole {
}

User "*" ------- "1..*" UserRole : > has
User "1..*"-- "1" House : > can configure
User "0..1" -- "*" Room : < is managed
User "1..*" ----- "*" Room : > may add

House "1" -- "*" Room : > has
House "1" -- "1" Address : > has
House "1" -- "1" GPS : > has

Room "1" -- "*" Device : > has
Room "1" -- "1" RoomDimensions : > has

Device "1" -- "*" Sensor : > can have
Sensor "*" -- "1" SensorType
Device "1" -- "*" Actuator : > can have
Actuator "*" -- "1" ActuatorType : > has

note top of SensorType : Available sensor types:\nTemperature and Humidity

@enduml
