@startuml
skinparam ParticipantPadding 50
    title Use Case: Get List of Actuator Types v5.1 - Main Success Scenario
    autonumber

participant ":AddActuatorToDeviceCTRL" as C
participant ":ActuatorTypeServiceImpl" as ATS
participant ":ActuatorTypeRepository" as ATR
participant ":ActuatorTypeMapper" as ATM


[o-> C : getListOfActuatorTypes()
activate C
C -> ATS : getListOfActuatorTypes()
activate ATS
ATS -> ATR : findAll()
activate ATR
ATR --> ATS : listOfActuatorTypes
deactivate ATR
loop for each actuatorType in listOfActuatorTypes
ATS -> ATS : actuatorTypeList = listOfActuatorType.forEach(actuatorType)
activate ATS
deactivate ATS
end
ATS --> C : actuatorTypeList
deactivate ATS

C -> ATM : domainToDTO(actuatorTypeList)
activate ATM
loop for each actuatorType in clonedListOfSensorTypes
    ATM -> ATM : ActuatorTypeDTO = domainToDTO(actuatorType)
    activate ATM
    deactivate ATM
    ATM -> ATM : actuatorTypeDTOList.add(SensorTypeDTO)
    activate ATM
    deactivate ATM
end
ATM --> C : actuatorTypeDTOList
deactivate ATM

[o<-- C : actuatorTypeDTOList
deactivate C
@enduml